/*
 * Sokol implementation of the render-module GPU sink: canned 2D quad
 * shader + 3D mesh shader (sokol-shdc generated, ADR 0015/0021), blend
 * pipeline variants, dynamic quad batching and indexed mesh playback
 * with depth (design D1–D7, F3).
 */
#include "platform/pipeline.h"
#include "platform/backend.h"
#include "render/render.h"
#include "math/efx_math.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "sokol_gfx.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* interleaved quad/billboard vertex: pos(3f) uv(2f) color(ub4n) = 24 bytes.
 * z is the already-divided NDC depth: 0 for 2D quads (the `quad` pipeline
 * ignores it), a real perspective depth for billboards/particles (the
 * `billboard` pipeline depth-tests it). */
typedef struct {
    float x, y, z;
    float u, v;
    uint8_t r, g, b, a;
} pipe_vertex;

/* interleaved mesh vertex: pos(3f) normal(3f) uv(2f) color(4f) = 48 bytes
 * (design D1: all attribute slots present, defaults filled at upload).
 * The full 4-element layout matches the shader input signature exactly;
 * D3D11 CreateInputLayout returns E_INVALIDARG for partial coverage. */
typedef struct {
    float x, y, z;
    float nx, ny, nz;
    float u, v;
    float r, g, b, a;
} pipe_mesh_vertex;

typedef struct {
    sg_image img;
    sg_view view;
    int wrap, filter; /* F6b per-texture sampler state */
    int mipmaps;      /* F6e: image carries a generated mip chain */
} pipe_tex;

/* F5a offscreen render target: env-default color+depth attachments plus a
 * texture view over the color image (sampling a target = texture coercion,
 * design D1) */
typedef struct {
    int w, h;
    sg_image color, depth;
    sg_view color_att, depth_att, color_tex;
} pipe_rt;

typedef struct {
    sg_buffer vbuf, ibuf;
    sg_buffer posed_vbuf; /* F7: dynamic posed vertex buffer (skinned only) */
    int has_posed;
    uint32_t posed_rev;   /* last uploaded pose revision */
    int index_count; /* 0 = non-indexed (draw vertex count) */
    int vertex_count;
} pipe_mesh_surface;

typedef struct {
    int surface_count;
    pipe_mesh_surface *surfaces;
} pipe_mesh;

typedef struct {
    sg_shader quad_shd;
    sg_pipeline quad_pip[3];
    sg_pipeline bill_pip[3]; /* F11: same shader/layout, depth test/no write */
    sg_shader mesh_shd;
    sg_pipeline mesh_pip[3];
    sg_pipeline mesh_pip_cw[3]; /* GL-family RT passes: projection y-flip
                                   mirrors winding (F5a) */
    /* F5b post passes: one shader + pipeline per pass type (uniform-driven,
       no permutations) */
    sg_shader post_shd[6];
    sg_pipeline post_pip[6];
    sg_sampler smp;
    sg_sampler smp_nearest; /* render-scale nearest blit */
    sg_sampler tex_smp[3][2][2]; /* F6b/F6e per-texture samplers, cached by
                                    (wrap, filter, mipmaps) */
    sg_view white_view; /* engine white texture, used for absent F4b maps */
    sg_buffer vbuf;
    size_t vbuf_size;       /* bytes; grown on demand (dynamic quad batch) */
    sg_buffer post_vbuf;    /* static fullscreen quad for post passes */
    pipe_vertex *scratch;
    int scratch_cap;
    int *run_first, *run_verts; /* per-run first vertex / vertex count */
    int run_cap;
    int *rec_boff;  /* F11: per-record first vertex (billboard/particles) */
    int *rec_bcnt;  /* F11: per-record vertex count */
    int rec_cap;
    int installed;
    int depth_remap; /* D3D11/Metal: fold 0..1 depth range into MVP */
    int rt_flip;     /* GL-family: flip y when rendering into RTs (F5a) */
    sg_attachments default_atts; /* invalid id = swapchain (capture only) */
    /* view-projection cache: consecutive mesh records usually share the
       camera snapshot, so recompose only when it (or the aspect) changes */
    int pv_valid;
    efx_camera3d pv_cam;
    float pv_aspect;
    int pv_flip;
    float pv[16];
} pipe_state;

static pipe_state P;

#define SOKOL_SHDC_IMPL
#include "shaders/quad.h" /* generated by sokol-shdc from shaders/quad.glsl (ADR 0021) */
#include "shaders/mesh.h" /* generated by sokol-shdc from shaders/mesh.glsl (ADR 0021) */
#include "shaders/post.h" /* generated by sokol-shdc from shaders/post.glsl (F5b) */

/* post pass programs, indexed by POST_* */
enum {
    POST_COLOR = 0,
    POST_BLUR,
    POST_BRIGHT,
    POST_MIX,
    POST_COMPOSITE,
    POST_COPY,
    POST_PROG_COUNT
};

/* fullscreen post vertex: NDC pos(2f) + uv(2f) */
typedef struct {
    float x, y, u, v;
} post_vertex;

#include "sokol_glue.h" /* sglue_swapchain + sglue_environment (impl in platform.c) */

/* F6e: number of mip levels for a full chain down to 1x1, driven by the
 * larger dimension (NPOT levels floor each step: max(1, n/2)) */
static int mip_level_count(int w, int h) {
    int n = w > h ? w : h;
    int count = 1;
    while (n > 1) {
        n >>= 1;
        count++;
    }
    return count;
}

/* F6e: 2x2 box-filter the chain on the CPU (deterministic across backends).
 * Level 0 aliases the caller's pixels; levels 1.. fill owned pointers that
 * the caller frees once sg_make_image has copied them. */
static void build_mip_chain(int w, int h, int levels, const uint8_t *rgba,
                            sg_image_data *data, uint8_t **owned) {
    data->mip_levels[0].ptr = rgba;
    data->mip_levels[0].size = (size_t)w * h * 4;
    const uint8_t *src = rgba;
    int cw = w, ch = h;
    for (int l = 1; l < levels; l++) {
        int nw = cw > 1 ? cw / 2 : 1;
        int nh = ch > 1 ? ch / 2 : 1;
        uint8_t *dst = malloc((size_t)nw * nh * 4);
        if (!dst) {
            owned[l] = NULL;
            return;
        }
        for (int y = 0; y < nh; y++) {
            for (int x = 0; x < nw; x++) {
                for (int c = 0; c < 4; c++) {
                    int sum = 0, cnt = 0;
                    for (int yy = y * 2; yy <= y * 2 + 1; yy++) {
                        if (yy >= ch) break;
                        for (int xx = x * 2; xx <= x * 2 + 1; xx++) {
                            if (xx >= cw) break;
                            sum += src[((size_t)yy * cw + xx) * 4 + c];
                            cnt++;
                        }
                    }
                    dst[((size_t)y * nw + x) * 4 + c] =
                        (uint8_t)((sum + cnt / 2) / cnt);
                }
            }
        }
        data->mip_levels[l].ptr = dst;
        data->mip_levels[l].size = (size_t)nw * nh * 4;
        owned[l] = dst;
        src = dst;
        cw = nw;
        ch = nh;
    }
}

static void *pipe_create_texture(void *ud, int w, int h, const uint8_t *rgba,
                                 int wrap, int filter, int mipmaps) {
    (void)ud;
    pipe_tex *t = calloc(1, sizeof(pipe_tex));
    if (!t) {
        return NULL;
    }
    sg_image_data data;
    memset(&data, 0, sizeof(data));
    uint8_t *owned[SG_MAX_MIPMAPS];
    memset(owned, 0, sizeof(owned));
    int levels = 1;
    if (mipmaps && rgba && (w > 1 || h > 1)) {
        levels = mip_level_count(w, h);
        if (levels > SG_MAX_MIPMAPS) {
            levels = SG_MAX_MIPMAPS;
        }
        build_mip_chain(w, h, levels, rgba, &data, owned);
        /* a failed level allocation degrades to the levels built so far */
        for (int l = 1; l < levels; l++) {
            if (!owned[l]) {
                levels = l;
                break;
            }
        }
        if (levels < 1) {
            levels = 1;
        }
    } else {
        data.mip_levels[0].ptr = rgba;
        data.mip_levels[0].size = (size_t)w * h * 4;
    }
    t->img = sg_make_image(&(sg_image_desc){
        .width = w,
        .height = h,
        .num_mipmaps = levels,
        .pixel_format = SG_PIXELFORMAT_RGBA8,
        .data = data,
    });
    for (int l = 1; l < levels; l++) {
        free(owned[l]);
    }
    t->view = sg_make_view(&(sg_view_desc){
        .texture.image = t->img,
    });
    t->wrap = wrap;
    t->filter = filter;
    t->mipmaps = levels > 1 ? 1 : 0;
    return t;
}

static void pipe_destroy_texture(void *ud, void *native) {
    (void)ud;
    pipe_tex *t = (pipe_tex *)native;
    if (t) {
        sg_destroy_view(t->view);
        sg_destroy_image(t->img);
        free(t);
    }
}

/* F5a: color image omits pixel_format/sample_count on purpose — sokol
 * defaults them from the environment (ADR 0025's env-default rule); the
 * depth image needs the environment's depth format explicitly */
static void *pipe_create_render_target(void *ud, int w, int h) {
    (void)ud;
    pipe_rt *t = calloc(1, sizeof(pipe_rt));
    if (!t) {
        return NULL;
    }
    t->w = w;
    t->h = h;
    sg_environment env = sglue_environment();
    t->color = sg_make_image(&(sg_image_desc){
        .width = w,
        .height = h,
        .usage = {.color_attachment = true},
    });
    t->depth = sg_make_image(&(sg_image_desc){
        .width = w,
        .height = h,
        .pixel_format = env.defaults.depth_format,
        .usage = {.depth_stencil_attachment = true},
    });
    if (t->color.id == SG_INVALID_ID || t->depth.id == SG_INVALID_ID) {
        if (t->color.id != SG_INVALID_ID) {
            sg_destroy_image(t->color);
        }
        if (t->depth.id != SG_INVALID_ID) {
            sg_destroy_image(t->depth);
        }
        free(t);
        return NULL;
    }
    t->color_att = sg_make_view(&(sg_view_desc){
        .color_attachment.image = t->color,
    });
    t->depth_att = sg_make_view(&(sg_view_desc){
        .depth_stencil_attachment.image = t->depth,
    });
    t->color_tex = sg_make_view(&(sg_view_desc){
        .texture.image = t->color,
    });
    return t;
}

static void pipe_destroy_render_target(void *ud, void *native) {
    (void)ud;
    pipe_rt *t = (pipe_rt *)native;
    if (t) {
        sg_destroy_view(t->color_att);
        sg_destroy_view(t->depth_att);
        sg_destroy_view(t->color_tex);
        sg_destroy_image(t->color);
        sg_destroy_image(t->depth);
        free(t);
    }
}

static void *pipe_create_mesh(void *ud, const efx_mesh_gpu_surface *surfs,
                              int count) {
    (void)ud;
    if (count < 1) {
        return NULL;
    }
    pipe_mesh *m = calloc(1, sizeof(pipe_mesh));
    if (!m) {
        return NULL;
    }
    m->surface_count = count;
    m->surfaces = calloc((size_t)count, sizeof(pipe_mesh_surface));
    if (!m->surfaces) {
        free(m);
        return NULL;
    }
    for (int i = 0; i < count; i++) {
        pipe_mesh_surface *d = &m->surfaces[i];
        d->vertex_count = surfs[i].vertex_count;
        d->index_count = surfs[i].index_count;
        d->vbuf = sg_make_buffer(&(sg_buffer_desc){
            .data = {.ptr = surfs[i].interleaved,
                     .size = (size_t)surfs[i].vertex_count *
                             sizeof(pipe_mesh_vertex)},
        });
        if (surfs[i].skinned) {
            /* F7: second buffer for CPU-posed vertices (same layout/size) */
            d->posed_vbuf = sg_make_buffer(&(sg_buffer_desc){
                .size = (size_t)surfs[i].vertex_count *
                        sizeof(pipe_mesh_vertex),
                .usage = {.vertex_buffer = true, .dynamic_update = true},
            });
            d->has_posed = 1;
        }
        if (surfs[i].indices) {
            d->ibuf = sg_make_buffer(&(sg_buffer_desc){
                .usage = {.index_buffer = true},
                .data = {.ptr = surfs[i].indices,
                         .size = (size_t)surfs[i].index_count *
                                 sizeof(uint32_t)},
            });
        }
    }
    return m;
}

static void pipe_destroy_mesh(void *ud, void *native) {
    (void)ud;
    pipe_mesh *m = (pipe_mesh *)native;
    if (m) {
        for (int i = 0; i < m->surface_count; i++) {
            sg_destroy_buffer(m->surfaces[i].vbuf);
            sg_destroy_buffer(m->surfaces[i].ibuf);
            if (m->surfaces[i].has_posed) {
                sg_destroy_buffer(m->surfaces[i].posed_vbuf);
            }
        }
        free(m->surfaces);
        free(m);
    }
}

static uint32_t pack_color(const float c[4]) {
    uint32_t r = (uint32_t)(c[0] * 255.0f + 0.5f);
    uint32_t g = (uint32_t)(c[1] * 255.0f + 0.5f);
    uint32_t b = (uint32_t)(c[2] * 255.0f + 0.5f);
    uint32_t a = (uint32_t)(c[3] * 255.0f + 0.5f);
    return (a << 24) | (b << 16) | (g << 8) | r;
}

static pipe_vertex emit_vert(const efx_quad_record *r, int i, int flip_y) {
    /* corner i in strip order: TL, TR, BL, BR; local space is 0..w, 0..h */
    static const float lu[4] = {0, 1, 0, 1};
    static const float lv[4] = {0, 0, 1, 1};
    static const float su[4] = {0, 1, 0, 1};
    static const float sv[4] = {0, 0, 1, 1};
    pipe_vertex v;
    const uint32_t packed = pack_color(r->color);
    {
        float fx = r->m.a * lu[i] * r->w + r->m.c * lv[i] * r->h + r->m.tx;
        float fy = r->m.b * lu[i] * r->w + r->m.d * lv[i] * r->h + r->m.ty;
        v.x = 2.0f * fx / r->frame_w - 1.0f;
        v.y = 1.0f - 2.0f * fy / r->frame_h;
        /* GL-family backends land offscreen render output top-at-v=1,
           while sokol's image convention (and every upload) is top-at-v=0
           (ADR 0028: origin conventions are engine-owned). Rendering INTO
           a render target is flipped here so sampled content is upright
           on every backend; the default framebuffer is unaffected. */
        if (flip_y) {
            v.y = -v.y;
        }
        v.z = 0.0f; /* 2D quads ignore depth (pipeline compare ALWAYS) */
        v.u = (r->sx + su[i] * r->sw) / r->tw;
        v.v = (r->sy + sv[i] * r->sh) / r->th;
        v.r = (uint8_t)(packed & 0xff);
        v.g = (uint8_t)((packed >> 8) & 0xff);
        v.b = (uint8_t)((packed >> 16) & 0xff);
        v.a = (uint8_t)((packed >> 24) & 0xff);
    }
    return v;
}

/* append one quad in strip order; `bridge` continues the previous quad's
 * strip: duplicate its last vertex, then this quad's first vertex twice
 * (two degenerate triangles) */
static pipe_vertex *emit_quad(pipe_vertex *v, const efx_quad_record *r,
                              int flip_y, int bridge) {
    if (bridge) {
        v[0] = v[-1];
        v[1] = emit_vert(r, 0, flip_y);
        v += 2;
    }
    for (int i = 0; i < 4; i++) {
        *v++ = emit_vert(r, i, flip_y);
    }
    return v;
}


void efx_pipeline_install(void) {
    if (P.installed) {
        return;
    }
    memset(&P, 0, sizeof(P));

    P.quad_shd = sg_make_shader(quad_shader_desc(sg_query_backend()));
    P.mesh_shd = sg_make_shader(mesh_shader_desc(sg_query_backend()));

    static const sg_blend_state blends[3] = {
        /* alpha: src*sa + dst*(1-sa) */
        {.enabled = true,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA},
        /* additive: dst + src*sa */
        {.enabled = true,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE},
        /* subtractive: dst - src*sa */
        {.enabled = true,
         .op_rgb = SG_BLENDOP_SUBTRACT,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE,
         .op_alpha = SG_BLENDOP_SUBTRACT,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE},
    };

    for (int i = 0; i < 3; i++) {
        sg_pipeline_desc qd = {
            .shader = P.quad_shd,
            .primitive_type = SG_PRIMITIVETYPE_TRIANGLE_STRIP,
            .layout = {.buffers[0].stride = (int)sizeof(pipe_vertex),
                       .attrs = {[0] = {.format = SG_VERTEXFORMAT_FLOAT3},
                                 [1] = {.format = SG_VERTEXFORMAT_FLOAT2, .offset = 12},
                                 [2] = {.format = SG_VERTEXFORMAT_UBYTE4N, .offset = 20}}},
            /* color format: environment default (matches the swapchain
               and the capture attachments on every backend) */
            .colors[0] = {.blend = blends[i]},
            .depth = {.compare = SG_COMPAREFUNC_ALWAYS, .write_enabled = false},
            .cull_mode = SG_CULLMODE_NONE,
            .sample_count = 1,
        };
        P.quad_pip[i] = sg_make_pipeline(&qd);
        /* F11 billboard/oriented-quad pipeline: the same shader and vertex
           layout, but depth-tested against opaque geometry with no depth
           write, so particles and sprites are occluded without occluding
           one another (ADR 0039) */
        qd.depth.compare = SG_COMPAREFUNC_LESS_EQUAL;
        P.bill_pip[i] = sg_make_pipeline(&qd);
        /* mesh pipelines: indexed triangles, depth-tested and writing
           (design D4), backface culling on CCW front faces (design D6) */
        sg_pipeline_desc md = {
            .shader = P.mesh_shd,
            .primitive_type = SG_PRIMITIVETYPE_TRIANGLES,
            /* mesh surfaces always draw indexed; non-indexed surfaces get
               a synthesized identity index buffer at upload (render.c) */
            .index_type = SG_INDEXTYPE_UINT32,
            /* all four attribute slots are declared so the layout matches
               the shader input signature on every backend (D3D11
               CreateInputLayout rejects partial coverage); normal/uv are
               bound but unused until F4 reads them */
            .layout = {.buffers[0].stride = (int)sizeof(pipe_mesh_vertex),
                       .attrs = {[ATTR_mesh_a_pos] = {.format = SG_VERTEXFORMAT_FLOAT3, .offset = 0},
                                 [ATTR_mesh_a_normal] = {.format = SG_VERTEXFORMAT_FLOAT3, .offset = 12},
                                 [ATTR_mesh_a_uv] = {.format = SG_VERTEXFORMAT_FLOAT2, .offset = 24},
                                 [ATTR_mesh_a_color] = {.format = SG_VERTEXFORMAT_FLOAT4, .offset = 32}}},
            .colors[0] = {.blend = blends[i]},
            .depth = {.compare = SG_COMPAREFUNC_LESS_EQUAL,
                      .write_enabled = true},
            .cull_mode = SG_CULLMODE_BACK,
            .face_winding = SG_FACEWINDING_CCW,
            .sample_count = 1,
        };
        P.mesh_pip[i] = sg_make_pipeline(&md);
        md.face_winding = SG_FACEWINDING_CW;
        P.mesh_pip_cw[i] = sg_make_pipeline(&md);
    }

    /* D3D11/Metal use a 0..1 depth range: fold the GL-style (-1..1)
       projection into clip space at playback (design D3/D4) */
    P.depth_remap = sg_query_features().origin_top_left ? 1 : 0;
    /* GL-family backends land offscreen render output top-at-v=1 (ADR
       0028): rendering INTO a render target flips y engine-side */
    P.rt_flip = P.depth_remap ? 0 : 1;

    P.smp = sg_make_sampler(&(sg_sampler_desc){.min_filter = SG_FILTER_LINEAR,
                                               .mag_filter = SG_FILTER_LINEAR});
    P.smp_nearest = sg_make_sampler(&(sg_sampler_desc){
        .min_filter = SG_FILTER_NEAREST, .mag_filter = SG_FILTER_NEAREST});
    P.vbuf_size = 256 * 1024;
    P.vbuf = sg_make_buffer(&(sg_buffer_desc){
        .size = P.vbuf_size,
        .usage = {.vertex_buffer = true, .dynamic_update = true},
    });

    /* F5b post passes: a static fullscreen quad (triangle strip, top-left
       uv origin) and one uniform-driven pipeline per pass type */
    static const post_vertex post_quad[4] = {
        {-1.0f, 1.0f, 0.0f, 0.0f},
        {1.0f, 1.0f, 1.0f, 0.0f},
        {-1.0f, -1.0f, 0.0f, 1.0f},
        {1.0f, -1.0f, 1.0f, 1.0f},
    };
    P.post_vbuf = sg_make_buffer(&(sg_buffer_desc){
        .data = {.ptr = post_quad, .size = sizeof(post_quad)},
    });
    P.post_shd[POST_COLOR] = sg_make_shader(post_color_shader_desc(sg_query_backend()));
    P.post_shd[POST_BLUR] = sg_make_shader(post_blur_shader_desc(sg_query_backend()));
    P.post_shd[POST_BRIGHT] = sg_make_shader(post_bright_shader_desc(sg_query_backend()));
    P.post_shd[POST_MIX] = sg_make_shader(post_mix_shader_desc(sg_query_backend()));
    P.post_shd[POST_COMPOSITE] = sg_make_shader(post_composite_shader_desc(sg_query_backend()));
    P.post_shd[POST_COPY] = sg_make_shader(post_copy_shader_desc(sg_query_backend()));
    for (int i = 0; i < POST_PROG_COUNT; i++) {
        P.post_pip[i] = sg_make_pipeline(&(sg_pipeline_desc){
            .shader = P.post_shd[i],
            .primitive_type = SG_PRIMITIVETYPE_TRIANGLE_STRIP,
            .layout = {.buffers[0].stride = (int)sizeof(post_vertex),
                       .attrs = {[0] = {.format = SG_VERTEXFORMAT_FLOAT2},
                                 [1] = {.format = SG_VERTEXFORMAT_FLOAT2, .offset = 8}}},
            .depth = {.compare = SG_COMPAREFUNC_ALWAYS, .write_enabled = false},
            .cull_mode = SG_CULLMODE_NONE,
            .sample_count = 1,
        });
    }
    P.installed = 1;

    static const efx_render_sink sink = {
        NULL, pipe_create_texture, pipe_destroy_texture,
        pipe_create_mesh, pipe_destroy_mesh, NULL,
        pipe_create_render_target, pipe_destroy_render_target,
    };
    efx_render_install_sink(&sink);
    uint64_t white = efx_render_white_texture(); /* engine-owned 1x1 white (D5) */
    pipe_tex *wt = (pipe_tex *)efx_render_texture_native(white);
    P.white_view = wt ? wt->view : (sg_view){0}; /* absent F4b maps fall back */
}

/* 3D camera + mesh playback (F3): per record, compose MVP from the
 * recorded camera and draw every surface in surface order (design
 * D3/D4/D7); equal-depth fragments resolve by record order because the
 * playback order is the record order */
static const float *view_projection(const efx_camera3d *cam, float aspect,
                                    int flip) {
    if (P.pv_valid && P.pv_aspect == aspect && P.pv_flip == flip &&
        memcmp(&P.pv_cam, cam, sizeof(*cam)) == 0) {
        return P.pv;
    }
    float up[3] = {0, 1, 0};
    float view[16], proj[16];
    efx_math_look_at(view, cam->pos, cam->target, up);
    efx_math_perspective(proj, cam->fov, aspect, cam->near_z, cam->far_z);
    efx_math_mul(P.pv, proj, view);
    if (flip) {
        /* GL-family RT passes: flip y so the attachment lands in sokol's
           top-at-v=0 image convention (F5a, ADR 0028); winding is
           compensated by the CW pipeline variants */
        for (int c = 0; c < 4; c++) {
            P.pv[c * 4 + 1] = -P.pv[c * 4 + 1];
        }
    }
    P.pv_cam = *cam;
    P.pv_aspect = aspect;
    P.pv_flip = flip;
    P.pv_valid = 1;
    return P.pv;
}

/* pass-action builder (moved from platform.c: playback owns its passes) */
static sg_pass_action pipe_pass_action(const float clear[4]) {
    sg_pass_action pa;
    memset(&pa, 0, sizeof(pa));
    pa.colors[0].load_action = SG_LOADACTION_CLEAR;
    pa.colors[0].clear_value = (sg_color){clear[0], clear[1], clear[2], clear[3]};
    /* F3 depth: cleared to far (1.0) each pass (design D4) */
    pa.depth.load_action = SG_LOADACTION_CLEAR;
    pa.depth.clear_value = 1.0f;
    return pa;
}

/* the default segment renders into the swapchain, or into the capture
   attachments when the platform overrides them (Metal goldens) */
static void begin_default_pass(const float clear[4]) {
    if (P.default_atts.colors[0].id != SG_INVALID_ID) {
        sg_begin_pass(&(sg_pass){
            .action = pipe_pass_action(clear),
            .attachments = P.default_atts,
        });
    } else {
        sg_begin_pass(&(sg_pass){
            .action = pipe_pass_action(clear),
            .swapchain = sglue_swapchain(),
        });
    }
}

void efx_pipeline_set_default_attachments(void *atts) {
    if (atts) {
        P.default_atts = *(sg_attachments *)atts;
    } else {
        memset(&P.default_atts, 0, sizeof(P.default_atts));
    }
}

/* texture coercion (F5a design D1): a sampling handle resolves through the
 * texture registry first, then the render-target registry */
static sg_view view_for_handle(uint64_t h) {
    pipe_tex *t = (pipe_tex *)efx_render_texture_native(h);
    if (t) {
        return t->view;
    }
    pipe_rt *rt = (pipe_rt *)efx_render_target_native(h);
    return rt ? rt->color_tex : (sg_view){0};
}

/* F6b/F6e: get-or-create the cached sampler for a (wrap, filter, mipmaps) set */
static sg_sampler tex_sampler(int wrap, int filter, int mipmaps) {
    if (wrap < 0 || wrap > 2) {
        wrap = EFX_TEX_WRAP_REPEAT;
    }
    if (filter != EFX_FILTER_NEAREST && filter != EFX_FILTER_LINEAR) {
        filter = EFX_FILTER_LINEAR;
    }
    mipmaps = mipmaps ? 1 : 0;
    if (P.tex_smp[wrap][filter][mipmaps].id == SG_INVALID_ID) {
        sg_filter f = filter == EFX_FILTER_NEAREST ? SG_FILTER_NEAREST
                                                   : SG_FILTER_LINEAR;
        sg_wrap w = wrap == EFX_TEX_WRAP_CLAMP
                        ? SG_WRAP_CLAMP_TO_EDGE
                        : wrap == EFX_TEX_WRAP_MIRROR ? SG_WRAP_MIRRORED_REPEAT
                                                      : SG_WRAP_REPEAT;
        P.tex_smp[wrap][filter][mipmaps] = sg_make_sampler(&(sg_sampler_desc){
            .min_filter = f,
            .mag_filter = f,
            .mipmap_filter = mipmaps ? f : SG_FILTER_NEAREST,
            .wrap_u = w,
            .wrap_v = w,
        });
    }
    return P.tex_smp[wrap][filter][mipmaps];
}

/* per-sample sampler: a texture's own sampler, or the default for absent
 * maps / render targets / non-texture handles */
static sg_sampler sampler_for_handle(uint64_t h) {
    pipe_tex *t = (pipe_tex *)efx_render_texture_native(h);
    return t ? tex_sampler(t->wrap, t->filter, t->mipmaps) : P.smp;
}

static void play_mesh_record(const efx_mesh_record *mr, float aspect, int flip) {
    pipe_mesh *m = (pipe_mesh *)efx_render_mesh_native(mr->mesh);
    if (!m) {
        return;
    }
    float mvp[16];
    efx_math_mul(mvp, view_projection(&mr->camera, aspect, flip), mr->transform);
    if (P.depth_remap) {
        /* row 2 of the clip matrix: z' = 0.5*z_clip + 0.5*w_clip maps the
           GL-style (-1..1) range onto the D3D11/Metal (0..1) range;
           monotonic, so depth comparisons and ties are unchanged. Row 3
           carries the perspective w in every column (not just the
           translation), so the fold must cover all four columns
           (ADR 0025). */
        for (int c = 0; c < 4; c++) {
            mvp[c * 4 + 2] = 0.5f * mvp[c * 4 + 2] + 0.5f * mvp[c * 4 + 3];
        }
    }

    vs_params_t vs;
    memcpy(vs.mvp, mvp, sizeof(mvp));
    memcpy(vs.model, mr->transform, sizeof(vs.model));
    efx_math_normal_matrix(vs.normal_mat, mr->transform);

    fs_params_t fs;
    memset(&fs, 0, sizeof(fs));
    fs.tint[0] = mr->color[0];
    fs.tint[1] = mr->color[1];
    fs.tint[2] = mr->color[2];
    fs.tint[3] = mr->color[3];
    fs.camera_pos[0] = mr->camera.pos[0];
    fs.camera_pos[1] = mr->camera.pos[1];
    fs.camera_pos[2] = mr->camera.pos[2];
    for (int i = 0; i < EFX_MAX_POINT_LIGHTS; i++) {
        const efx_point_light *p = &mr->lights.points[i];
        if (!p->enabled) {
            continue;
        }
        fs.point_pos[i][0] = p->pos[0];
        fs.point_pos[i][1] = p->pos[1];
        fs.point_pos[i][2] = p->pos[2];
        fs.point_pos[i][3] = p->range;
        fs.point_color[i][0] = p->color[0];
        fs.point_color[i][1] = p->color[1];
        fs.point_color[i][2] = p->color[2];
        fs.point_color[i][3] = 1.0f;
    }
    if (mr->lights.directional.enabled) {
        fs.dir_dir[0] = mr->lights.directional.dir[0];
        fs.dir_dir[1] = mr->lights.directional.dir[1];
        fs.dir_dir[2] = mr->lights.directional.dir[2];
        fs.dir_dir[3] = 1.0f;
        fs.dir_color[0] = mr->lights.directional.color[0];
        fs.dir_color[1] = mr->lights.directional.color[1];
        fs.dir_color[2] = mr->lights.directional.color[2];
    }

    sg_apply_pipeline(flip ? P.mesh_pip_cw[mr->blend] : P.mesh_pip[mr->blend]);
    sg_apply_uniforms(UB_vs_params, &(sg_range){.ptr = &vs, .size = sizeof(vs)});
    uint64_t white = efx_render_white_texture(); /* absent-map fallback (D3) */
    pipe_tex *white_tex = (pipe_tex *)efx_render_texture_native(white);
    sg_view white_view = white_tex ? white_tex->view : P.white_view;
    for (int i = 0; i < m->surface_count; i++) {
        pipe_mesh_surface *s = &m->surfaces[i];
        if (!s->index_count) {
            continue;
        }
        efx_material mat;
        efx_render_mesh_surface_material(mr->mesh, i, &mat);
        memcpy(fs.ambient, mat.ambient, sizeof(fs.ambient));
        memcpy(fs.diffuse, mat.diffuse, sizeof(fs.diffuse));
        memcpy(fs.specular, mat.specular, sizeof(fs.specular));
        memcpy(fs.emissive, mat.emissive, sizeof(fs.emissive));
        fs.mat_params[0] = mat.shininess;

        /* F4b D3: bind all five maps; absent ones fall back to the engine
           white texture (color maps sample (1,1,1,1); the mask samples
           alpha 1, so it never discards). One shared sampler for all. */
        uint64_t maps[5] = {mat.ambient_map, mat.diffuse_map, mat.specular_map,
                            mat.emissive_map, mat.alpha_mask};
        sg_bindings bnd = {0};
        if (mr->skinned && s->has_posed) {
            /* F7: push the CPU-posed vertices once per pose revision, then
               draw the posed buffer instead of the bind-pose buffer */
            uint32_t rev = efx_render_mesh_pose_revision(mr->mesh);
            if (rev != s->posed_rev) {
                const float *p = efx_render_mesh_posed(mr->mesh, i);
                if (p) {
                    sg_update_buffer(s->posed_vbuf, &(sg_range){
                        .ptr = p,
                        .size = (size_t)s->vertex_count *
                                sizeof(pipe_mesh_vertex)});
                    s->posed_rev = rev;
                }
            }
            bnd.vertex_buffers[0] = s->posed_vbuf;
        } else {
            bnd.vertex_buffers[0] = s->vbuf;
        }
        bnd.index_buffer = s->ibuf;
        for (int k = 0; k < 5; k++) {
            sg_view map_view = view_for_handle(maps[k]);
            bnd.views[k] = map_view.id != SG_INVALID_ID ? map_view : white_view;
            bnd.samplers[k] = sampler_for_handle(maps[k]);
        }
        sg_apply_bindings(&bnd);
        /* documented order: pipeline -> bindings -> uniforms -> draw */
        sg_apply_uniforms(UB_fs_params,
                          &(sg_range){.ptr = &fs, .size = sizeof(fs)});
        sg_draw(0, s->index_count, 1);
    }
}

/* ------------------------------------------------- F5b post passes */

/* scene dimension at the current render scale (rounded up) */
static int post_dim(int surface, float scale) {
    if (surface <= 0) {
        return 1;
    }
    int v = (int)ceilf((float)surface * scale);
    return v < 1 ? 1 : v;
}

/* begin a pass on a target handle (0 = the default surface/capture) */
static void post_begin_pass(uint64_t dst, const float clear[4]) {
    if (!dst) {
        begin_default_pass(clear);
        return;
    }
    pipe_rt *rt = (pipe_rt *)efx_render_target_native(dst);
    if (!rt) {
        begin_default_pass(clear);
        return;
    }
    sg_begin_pass(&(sg_pass){
        .action = pipe_pass_action(clear),
        .attachments = {.colors[0] = rt->color_att,
                        .depth_stencil = rt->depth_att},
    });
}

/* one fullscreen post pass: bind up to two sources (one sampler), apply the
 * pass's fragment uniforms when `fs` is given, draw, end. y-flip follows the
 * destination surface. */
static void post_draw(int prog, uint64_t dst, uint64_t tex_a, uint64_t tex_b,
                      sg_sampler smp, const void *fs, size_t fs_size) {
    static const float clear[4] = {0, 0, 0, 0};
    post_begin_pass(dst, clear);
    sg_apply_pipeline(P.post_pip[prog]);
    post_vs_params_t vs;
    memset(&vs, 0, sizeof(vs));
    vs.post_params[0] = dst && P.rt_flip ? -1.0f : 1.0f;
    sg_apply_uniforms(UB_post_vs_params, &(sg_range){.ptr = &vs, .size = sizeof(vs)});
    sg_bindings bnd = {0};
    bnd.vertex_buffers[0] = P.post_vbuf;
    bnd.views[0] = view_for_handle(tex_a);
    bnd.samplers[0] = smp;
    if (tex_b) {
        bnd.views[1] = view_for_handle(tex_b);
        bnd.samplers[1] = smp;
    }
    sg_apply_bindings(&bnd);
    if (fs) {
        sg_apply_uniforms(1, &(sg_range){.ptr = fs, .size = fs_size});
    }
    sg_draw(0, 4, 1);
    sg_end_pass();
}

/* separable blur: horizontal `src` -> `t0`, then vertical `t0` -> `t1` */
static void blur_two_pass(uint64_t src, uint64_t t0, uint64_t t1, float dx,
                          float dy) {
    post_blur_params_t bu;
    memset(&bu, 0, sizeof(bu));
    bu.blur_dir[0] = dx;
    post_draw(POST_BLUR, t0, src, 0, P.smp, &bu, sizeof(bu));
    memset(&bu, 0, sizeof(bu));
    bu.blur_dir[1] = dy;
    post_draw(POST_BLUR, t1, t0, 0, P.smp, &bu, sizeof(bu));
}

/* execute one chain entry: read `src` (src_w x src_h), write the mixed
 * result to `dst` (0 = default surface). The internal pass structure is
 * registry-owned and invisible to scripts. */
static void run_post_entry(const efx_post_entry *e, uint64_t src, int src_w,
                           int src_h, uint64_t dst) {
    switch (e->effect) {
    case EFX_POST_COLOR_FILTER: {
        post_color_params_t u;
        memset(&u, 0, sizeof(u));
        u.color_params[0] = e->u.color_filter.brightness;
        u.color_params[1] = e->u.color_filter.contrast;
        u.color_params[2] = e->u.color_filter.saturation;
        u.color_params[3] = e->mix;
        memcpy(u.tint, e->u.color_filter.tint, sizeof(u.tint));
        post_draw(POST_COLOR, dst, src, 0, P.smp, &u, sizeof(u));
        break;
    }
    case EFX_POST_BLUR: {
        float radius = e->u.blur.radius;
        post_mix_params_t mu;
        memset(&mu, 0, sizeof(mu));
        mu.mix_params[0] = e->mix;
        if (radius > 8.0f) {
            /* downsample chain: blur at half res, then upsample in the mix
               pass (bilinear sampling of the half-size result) */
            int hw = post_dim(src_w, 0.5f), hh = post_dim(src_h, 0.5f);
            uint64_t h0 = efx_render_post_half_target(0, hw, hh);
            uint64_t h1 = efx_render_post_half_target(1, hw, hh);
            if (!h0 || !h1) {
                break;
            }
            post_draw(POST_COPY, h0, src, 0, P.smp, NULL, 0);
            blur_two_pass(h0, h1, h0, (radius * 0.5f) / (4.0f * (float)hw),
                          (radius * 0.5f) / (4.0f * (float)hh));
            post_draw(POST_MIX, dst, src, h0, P.smp, &mu, sizeof(mu));
        } else {
            uint64_t t0 = efx_render_post_temp_target(2, src_w, src_h);
            uint64_t t1 = efx_render_post_temp_target(3, src_w, src_h);
            if (!t0 || !t1) {
                break;
            }
            blur_two_pass(src, t0, t1, radius / (4.0f * (float)src_w),
                          radius / (4.0f * (float)src_h));
            post_draw(POST_MIX, dst, src, t1, P.smp, &mu, sizeof(mu));
        }
        break;
    }
    case EFX_POST_BLOOM: {
        /* threshold at half res, blur, then additive composite at full res */
        int hw = post_dim(src_w, 0.5f), hh = post_dim(src_h, 0.5f);
        uint64_t h0 = efx_render_post_half_target(0, hw, hh);
        uint64_t h1 = efx_render_post_half_target(1, hw, hh);
        if (!h0 || !h1) {
            break;
        }
        post_bright_params_t bp;
        memset(&bp, 0, sizeof(bp));
        bp.bright_params[0] = e->u.bloom.threshold;
        post_draw(POST_BRIGHT, h0, src, 0, P.smp, &bp, sizeof(bp));
        blur_two_pass(h0, h1, h0, 2.0f / (float)hw, 2.0f / (float)hh);
        post_composite_params_t cp;
        memset(&cp, 0, sizeof(cp));
        cp.comp_params[0] = e->u.bloom.strength;
        cp.comp_params[1] = e->mix;
        post_draw(POST_COMPOSITE, dst, src, h0, P.smp, &cp, sizeof(cp));
        break;
    }
    default:
        break;
    }
}

/* the default target's resolve: run the chain in array order through
 * engine-owned temporaries, or blit the scene when only the render scale
 * changed. `scene` holds the rendered default segment. */
static void run_post_chain(uint64_t scene, int sw, int sh) {
    int count = 0;
    efx_post_entry entries[EFX_POST_MAX_ENTRIES];
    efx_render_post_effects(entries, &count);
    if (count == 0) {
        float scale = 1.0f;
        int filter = EFX_FILTER_LINEAR;
        efx_render_render_scale(&scale, &filter);
        sg_sampler smp = filter == EFX_FILTER_NEAREST ? P.smp_nearest : P.smp;
        post_draw(POST_COPY, 0, scene, 0, smp, NULL, 0);
        return;
    }
    uint64_t src = scene;
    for (int i = 0; i < count; i++) {
        int last = i == count - 1;
        uint64_t dst = last ? 0 : efx_render_post_temp_target(i & 1, sw, sh);
        run_post_entry(&entries[i], src, sw, sh, dst);
        if (!last) {
            src = dst;
        }
    }
}

/* ------------------------------------------------- F11 billboard playback */

/* grow the shared scratch to hold at least `need` vertices */
static int scratch_reserve(int need) {
    if (need <= P.scratch_cap) {
        return 1;
    }
    int cap = P.scratch_cap ? P.scratch_cap : 64;
    while (cap < need) {
        cap *= 2;
    }
    pipe_vertex *grown = realloc(P.scratch, (size_t)cap * sizeof(pipe_vertex));
    if (!grown) {
        return 0;
    }
    P.scratch = grown;
    P.scratch_cap = cap;
    return 1;
}

/* per-record aspect and RT flip (default surface = scene target when post
 * is active; a render-target record uses the target's extent) */
static float rec_aspect(const efx_record *r, int use_post, int scene_w,
                        int scene_h, int vw, int vh) {
    int w, h;
    if (r->target) {
        efx_render_target_size(r->target, &w, &h);
    } else {
        w = use_post ? scene_w : vw;
        h = use_post ? scene_h : vh;
    }
    return (w > 0 && h > 0) ? (float)w / (float)h : 4.0f / 3.0f;
}

static int rec_flip(const efx_record *r, int use_post) {
    return P.rt_flip && (use_post || r->target != 0);
}

static void bill_clip(const float mvp[16], const float w[3], float out[3]) {
    float x = w[0], y = w[1], z = w[2];
    float cx = mvp[0] * x + mvp[4] * y + mvp[8] * z + mvp[12];
    float cy = mvp[1] * x + mvp[5] * y + mvp[9] * z + mvp[13];
    float cz = mvp[2] * x + mvp[6] * y + mvp[10] * z + mvp[14];
    float cw = mvp[3] * x + mvp[7] * y + mvp[11] * z + mvp[15];
    if (cw != 0.0f) {
        out[0] = cx / cw;
        out[1] = cy / cw;
        out[2] = cz / cw;
    } else {
        out[0] = cx;
        out[1] = cy;
        out[2] = cz;
    }
    if (P.depth_remap) {
        out[2] = 0.5f * out[2] + 0.5f;
    }
}

/* quad corners in strip order TL,TR,BL,BR */
static const float BILL_LX[4] = {-0.5f, 0.5f, -0.5f, 0.5f};
static const float BILL_LY[4] = {0.5f, 0.5f, -0.5f, -0.5f};
static const float BILL_SU[4] = {0, 1, 0, 1};
static const float BILL_SV[4] = {0, 0, 1, 1};

/* build rotated in-plane axes for a facing mode */
static void bill_axes(const efx_camera3d *cam, int facing, const float normal[3],
                      float rotation, float rr[3], float uu[3]) {
    float right[3], up[3];
    efx_render_billboard_basis(cam, facing, normal, right, up);
    float a = rotation * (float)(M_PI / 180.0);
    float cs = cosf(a), sn = sinf(a);
    for (int k = 0; k < 3; k++) {
        rr[k] = right[k] * cs + up[k] * sn;
        uu[k] = -right[k] * sn + up[k] * cs;
    }
}

static pipe_vertex *emit_billboard(pipe_vertex *v,
                                   const efx_billboard_record *b, float aspect,
                                   int flip) {
    const float *vp = view_projection(&b->camera, aspect, flip);
    float mvp[16];
    memcpy(mvp, vp, sizeof(mvp));
    float rr[3], uu[3];
    bill_axes(&b->camera, b->facing, b->normal, b->rotation, rr, uu);
    uint32_t packed = pack_color(b->color);
    for (int i = 0; i < 4; i++) {
        float w[3];
        for (int k = 0; k < 3; k++) {
            w[k] = b->pos[k] + rr[k] * (BILL_LX[i] * b->w) +
                   uu[k] * (BILL_LY[i] * b->h);
        }
        float ndc[3];
        bill_clip(mvp, w, ndc);
        v->x = ndc[0];
        v->y = ndc[1];
        v->z = ndc[2];
        v->u = (b->sx + BILL_SU[i] * b->sw) / (b->tw > 0 ? b->tw : 1.0f);
        v->v = (b->sy + BILL_SV[i] * b->sh) / (b->th > 0 ? b->th : 1.0f);
        v->r = (uint8_t)(packed & 0xff);
        v->g = (uint8_t)((packed >> 8) & 0xff);
        v->b = (uint8_t)((packed >> 16) & 0xff);
        v->a = (uint8_t)((packed >> 24) & 0xff);
        v++;
    }
    return v;
}

static void emit_particle_world(pipe_vertex out[4],
                                const efx_particle_view *p,
                                const efx_camera3d *cam, int facing,
                                const float normal[3], float aspect, int flip) {
    const float *vp = view_projection(cam, aspect, flip);
    float mvp[16];
    memcpy(mvp, vp, sizeof(mvp));
    float rr[3], uu[3];
    bill_axes(cam, facing, normal, p->angle, rr, uu);
    uint32_t packed = pack_color(p->color);
    float u0 = p->uv[0], v0 = p->uv[1], u1 = p->uv[2], v1 = p->uv[3];
    for (int i = 0; i < 4; i++) {
        float w[3];
        for (int k = 0; k < 3; k++) {
            w[k] = p->pos[k] + rr[k] * (BILL_LX[i] * p->size) +
                   uu[k] * (BILL_LY[i] * p->size);
        }
        float ndc[3];
        bill_clip(mvp, w, ndc);
        out[i].x = ndc[0];
        out[i].y = ndc[1];
        out[i].z = ndc[2];
        out[i].u = u0 + BILL_SU[i] * (u1 - u0);
        out[i].v = v0 + BILL_SV[i] * (v1 - v0);
        out[i].r = (uint8_t)(packed & 0xff);
        out[i].g = (uint8_t)((packed >> 8) & 0xff);
        out[i].b = (uint8_t)((packed >> 16) & 0xff);
        out[i].a = (uint8_t)((packed >> 24) & 0xff);
    }
}

static void emit_particle_screen(pipe_vertex out[4],
                                 const efx_particle_view *p,
                                 const efx_particle_record *pr, int flip) {
    efx_affine m = efx_camera_matrix(&pr->camera2d, pr->frame_w, pr->frame_h);
    uint32_t packed = pack_color(p->color);
    float u0 = p->uv[0], v0 = p->uv[1], u1 = p->uv[2], v1 = p->uv[3];
    for (int i = 0; i < 4; i++) {
        float cx = p->pos[0] + BILL_LX[i] * p->size;
        float cy = p->pos[1] + BILL_LY[i] * p->size;
        float fx = m.a * cx + m.c * cy + m.tx;
        float fy = m.b * cx + m.d * cy + m.ty;
        out[i].x = 2.0f * fx / (pr->frame_w > 0 ? pr->frame_w : 1.0f) - 1.0f;
        out[i].y = 1.0f - 2.0f * fy / (pr->frame_h > 0 ? pr->frame_h : 1.0f);
        if (flip) {
            out[i].y = -out[i].y;
        }
        out[i].z = 0.0f;
        out[i].u = u0 + BILL_SU[i] * (u1 - u0);
        out[i].v = v0 + BILL_SV[i] * (v1 - v0);
        out[i].r = (uint8_t)(packed & 0xff);
        out[i].g = (uint8_t)((packed >> 8) & 0xff);
        out[i].b = (uint8_t)((packed >> 16) & 0xff);
        out[i].a = (uint8_t)((packed >> 24) & 0xff);
    }
}

/* append a quad to a triangle strip, inserting degenerate triangles after
 * the first so consecutive particle quads are not bridged by a visible
 * triangle (the same trick the 2D quad run uses) */
static pipe_vertex *append_strip_quad(pipe_vertex *v, const pipe_vertex q[4],
                                      int first) {
    if (!first) {
        v[0] = v[-1];
        v[1] = q[0];
        v[2] = q[0];
        v += 3;
    }
    memcpy(v, q, sizeof(pipe_vertex) * 4);
    return v + 4;
}

/* world-space particle views sorted back-to-front (alpha batches only) */
typedef struct {
    const efx_particle_view *view;
    float depth;
} particle_sort;

static int particle_cmp(const void *a, const void *b) {
    const particle_sort *pa = a, *pb = b;
    if (pa->depth < pb->depth) return 1; /* farther first */
    if (pa->depth > pb->depth) return -1;
    return 0;
}

/* grow the shared scratch to hold at least the quad-record vertices */
static int ensure_scratch(int quad_count) {
    if (quad_count <= 0) {
        return 1;
    }
    int cap = quad_count * 6 + 4;
    if (cap > P.scratch_cap) {
        pipe_vertex *grown = realloc(P.scratch, (size_t)cap * sizeof(pipe_vertex));
        if (!grown) {
            return 0;
        }
        P.scratch = grown;
        P.scratch_cap = cap;
    }
    return 1;
}

/* grow a pair of parallel int arrays to hold at least `need` entries; the
 * call site's OOM branch is unchanged (both reallocs must succeed) */
static int grow_int_pair(int **a, int **b, int *cap, int need) {
    if (need <= *cap) {
        return 1;
    }
    int ncap = *cap ? *cap : 64;
    while (ncap < need) {
        ncap *= 2;
    }
    int *na = realloc(*a, (size_t)ncap * sizeof(int));
    int *nb = realloc(*b, (size_t)ncap * sizeof(int));
    if (na) *a = na;
    if (nb) *b = nb;
    if (!na || !nb) {
        return 0;
    }
    *cap = ncap;
    return 1;
}

/* emit every quad run into the scratch, recording each run's first vertex
 * and vertex count; returns the total vertex count */
static int emit_quad_runs(const efx_record *records, const efx_draw_run *runs,
                          int run_count, int *run_first, int *run_verts,
                          int use_post) {
    pipe_vertex *v = P.scratch;
    for (int ri = 0; ri < run_count; ri++) {
        run_first[ri] = (int)(v - P.scratch);
        int start = (int)(v - P.scratch);
        for (int q = 0; q < runs[ri].count; q++) {
            int flip = P.rt_flip &&
                       (use_post ||
                        records[runs[ri].start + q].target != 0);
            v = emit_quad(v, &records[runs[ri].start + q].u.quad, flip, q > 0);
        }
        run_verts[ri] = (int)(v - P.scratch) - start;
    }
    return (int)(v - P.scratch);
}

/* order world-space particle views back-to-front for an alpha batch */
static particle_sort *sort_particles_back_to_front(
    const efx_particle_record *pr, const efx_particle_view *views, int pc) {
    particle_sort *order = malloc((size_t)pc * sizeof(particle_sort));
    if (!order) {
        return NULL;
    }
    const float *cp = pr->camera.pos;
    float fwd[3] = {pr->camera.target[0] - cp[0],
                    pr->camera.target[1] - cp[1],
                    pr->camera.target[2] - cp[2]};
    float fl = sqrtf(fwd[0] * fwd[0] + fwd[1] * fwd[1] + fwd[2] * fwd[2]);
    if (fl > 0.0f) {
        fwd[0] /= fl; fwd[1] /= fl; fwd[2] /= fl;
    }
    for (int k = 0; k < pc; k++) {
        order[k].view = &views[k];
        order[k].depth =
            (views[k].pos[0] - cp[0]) * fwd[0] +
            (views[k].pos[1] - cp[1]) * fwd[1] +
            (views[k].pos[2] - cp[2]) * fwd[2];
    }
    qsort(order, (size_t)pc, sizeof(particle_sort), particle_cmp);
    return order;
}

/* F11: emit billboard and particle vertices after the quad batch (same
 * vertex format; drawn with the depth-tested billboard pipeline); returns the
 * total vertex count, or -1 on allocation failure */
static int emit_billboards_and_particles(const efx_record *records, int count,
                                         int *boff, int *bcnt, int use_post,
                                         int scene_w, int scene_h, int vw,
                                         int vh, int total) {
    for (int i = 0; i < count; i++) {
        const efx_record *r = &records[i];
        if (r->type == EFX_RECORD_BILLBOARD) {
            if (!scratch_reserve(total + 4)) return -1;
            pipe_vertex *v = P.scratch + total;
            v = emit_billboard(v, &r->u.billboard,
                              rec_aspect(r, use_post, scene_w, scene_h, vw, vh),
                              rec_flip(r, use_post));
            boff[i] = total;
            bcnt[i] = 4;
            total += 4;
        } else if (r->type == EFX_RECORD_PARTICLES) {
            uint64_t sys = r->u.particles.system;
            int pc = 0;
            const efx_particle_view *views =
                efx_render_particles_views(sys, &pc);
            int space = efx_render_particles_space(sys);
            if (pc <= 0 || !views) {
                continue;
            }
            /* reserve 4 verts per quad plus 3 bridge verts between them */
            int need = pc * 4 + (pc - 1) * 3;
            if (!scratch_reserve(total + need)) return -1;
            pipe_vertex *v = P.scratch + total;
            int start = total;
            int blend = r->u.particles.blend;
            pipe_vertex q4[4];
            if (space == EFX_SPACE_WORLD) {
                int facing = efx_render_particles_facing(sys);
                float normal[3];
                efx_render_particles_normal(sys, normal);
                float aspect = rec_aspect(r, use_post, scene_w, scene_h, vw, vh);
                int flip = rec_flip(r, use_post);
                if (blend == EFX_BLEND_ALPHA && pc > 1) {
                    particle_sort *order =
                        sort_particles_back_to_front(&r->u.particles, views, pc);
                    if (!order) return -1;
                    for (int k = 0; k < pc; k++) {
                        emit_particle_world(q4, order[k].view,
                                            &r->u.particles.camera, facing,
                                            normal, aspect, flip);
                        v = append_strip_quad(v, q4, k == 0);
                    }
                    free(order);
                } else {
                    for (int k = 0; k < pc; k++) {
                        emit_particle_world(q4, &views[k],
                                            &r->u.particles.camera, facing,
                                            normal, aspect, flip);
                        v = append_strip_quad(v, q4, k == 0);
                    }
                }
            } else {
                int flip = rec_flip(r, use_post);
                for (int k = 0; k < pc; k++) {
                    emit_particle_screen(q4, &views[k], &r->u.particles, flip);
                    v = append_strip_quad(v, q4, k == 0);
                }
            }
            boff[i] = start;
            bcnt[i] = need;
            total += need;
        }
    }
    return total;
}

/* upload the emitted vertices into the shared dynamic vertex buffer */
static void upload_vertices(int vcount) {
    if (vcount <= 0) {
        return;
    }
    size_t bytes = (size_t)vcount * sizeof(pipe_vertex);
    if (bytes > P.vbuf_size) {
        /* sokol buffers are fixed-size: replace with a larger one
           (updated once per frame, so a fresh buffer is safe here) */
        size_t size = P.vbuf_size;
        while (size < bytes) {
            size *= 2;
        }
        sg_destroy_buffer(P.vbuf);
        P.vbuf = sg_make_buffer(&(sg_buffer_desc){
            .size = size,
            .usage = {.vertex_buffer = true, .dynamic_update = true},
        });
        P.vbuf_size = size;
    }
    sg_update_buffer(P.vbuf, &(sg_range){.ptr = P.scratch, .size = bytes});
}

/* apply a pipeline, bind the shared vertex buffer + texture view/sampler and
 * draw a vertex range (skipped when the texture is not live) */
static void draw_textured(sg_pipeline pip, uint64_t handle, int first,
                          int count) {
    sg_apply_pipeline(pip);
    sg_bindings bnd = {0};
    bnd.vertex_buffers[0] = P.vbuf;
    sg_view view = view_for_handle(handle);
    if (view.id != SG_INVALID_ID) {
        bnd.views[0] = view;
        bnd.samplers[0] = sampler_for_handle(handle);
        sg_apply_bindings(&bnd);
        sg_draw(first, count, 1);
    }
}

/* BEGIN_TARGET: close the current pass and open the render target's; falls
 * back to the default surface when the target is not live (unreachable when
 * validation holds) */
static void switch_to_target(uint64_t target, const float clear[4],
                             int *cur_w, int *cur_h, uint64_t default_surface,
                             int use_post, int scene_w, int scene_h, int vw,
                             int vh) {
    sg_end_pass();
    pipe_rt *rt = (pipe_rt *)efx_render_target_native(target);
    if (rt) {
        sg_begin_pass(&(sg_pass){
            .action = pipe_pass_action(clear),
            .attachments = {.colors[0] = rt->color_att,
                            .depth_stencil = rt->depth_att},
        });
        *cur_w = rt->w;
        *cur_h = rt->h;
    } else {
        post_begin_pass(default_surface, clear);
        *cur_w = use_post ? scene_w : vw;
        *cur_h = use_post ? scene_h : vh;
    }
}

/* END_TARGET: close the render target's pass and reopen the default surface */
static void switch_to_default(const float clear[4], int *cur_w, int *cur_h,
                              uint64_t default_surface, int use_post,
                              int scene_w, int scene_h, int vw, int vh) {
    sg_end_pass();
    post_begin_pass(default_surface, clear);
    *cur_w = use_post ? scene_w : vw;
    *cur_h = use_post ? scene_h : vh;
}

/* pass management (F5a/F5b): the default surface pass opens eagerly
 * (clear-only frames render exactly as before); BEGIN/END control records
 * switch between the default surface and render-target attachments. With post
 * active the default surface is the scene target; the chain resolves it to the
 * real default afterwards. Then interleave run draws and mesh records in
 * record order. */
static void play_records(const efx_record *records, int count,
                         const efx_draw_run *runs, int run_count,
                         const int *run_first, const int *run_verts,
                         const int *boff, const int *bcnt, int use_post,
                         int scene_w, int scene_h, int vw, int vh,
                         uint64_t default_surface) {
    float frame_clear[4];
    efx_render_clear_color(frame_clear);
    int cur_w = use_post ? scene_w : vw;
    int cur_h = use_post ? scene_h : vh;
    post_begin_pass(default_surface, frame_clear);
    int run_i = 0;
    for (int i = 0; i < count; i++) {
        const efx_record *r = &records[i];
        if (r->type == EFX_RECORD_BEGIN_TARGET) {
            switch_to_target(r->u.begin_target.target, r->u.begin_target.clear,
                             &cur_w, &cur_h, default_surface, use_post,
                             scene_w, scene_h, vw, vh);
            continue;
        }
        if (r->type == EFX_RECORD_END_TARGET) {
            switch_to_default(frame_clear, &cur_w, &cur_h, default_surface,
                              use_post, scene_w, scene_h, vw, vh);
            continue;
        }
        float aspect =
            (cur_w > 0 && cur_h > 0) ? (float)cur_w / (float)cur_h : 4.0f / 3.0f;
        if (r->type == EFX_RECORD_QUAD) {
            if (run_i < run_count && runs[run_i].start == i) {
                draw_textured(P.quad_pip[runs[run_i].blend],
                              runs[run_i].texture, run_first[run_i],
                              run_verts[run_i]);
                run_i++;
                i += runs[run_i - 1].count - 1;
            }
        } else if (r->type == EFX_RECORD_MESH) {
            play_mesh_record(&r->u.mesh, aspect,
                             P.rt_flip && (use_post || r->target != 0));
        } else if (r->type == EFX_RECORD_BILLBOARD && bcnt[i] > 0) {
            draw_textured(P.bill_pip[r->u.billboard.blend],
                          r->u.billboard.texture, boff[i], bcnt[i]);
        } else if (r->type == EFX_RECORD_PARTICLES && bcnt[i] > 0) {
            int space = efx_render_particles_space(r->u.particles.system);
            int blend = r->u.particles.blend;
            uint64_t tex = efx_render_particles_texture(r->u.particles.system);
            draw_textured(space == EFX_SPACE_WORLD ? P.bill_pip[blend]
                                                   : P.quad_pip[blend],
                          tex, boff[i], bcnt[i]);
        }
    }
    sg_end_pass();
    if (use_post) {
        run_post_chain(default_surface, scene_w, scene_h);
    }
}

void efx_pipeline_play(void) {
    if (!P.installed) {
        return;
    }
    int count = 0;
    const efx_record *records = efx_render_records(&count);
    int run_count = 0;
    const efx_draw_run *runs = count > 0 ? efx_render_runs(&run_count) : NULL;
    if (run_count > 0 && !runs) {
        return;
    }

    int vw = 0, vh = 0;
    efx_render_viewport(&vw, &vh);

    /* quad scratch sizing: only the quad records are emitted */
    int quad_count = 0;
    for (int i = 0; i < count; i++) {
        if (records[i].type == EFX_RECORD_QUAD) {
            quad_count++;
        }
    }
    if (!ensure_scratch(quad_count)) {
        return;
    }

    /* F2 playback: emit ALL quad runs into one dynamic-buffer update
       (multiple updates per frame are unreliable on Metal/D3D11), then
       interleave run draws and mesh records in record order */
    if (!grow_int_pair(&P.run_first, &P.run_verts, &P.run_cap, run_count)) {
        return;
    }
    int *run_first = P.run_first;
    int *run_verts = P.run_verts;
    /* F5b: when a chain is set or the render scale is not 1, the default
       segment renders into the engine-owned implicit scene target (an RT),
       so its records need the GL-family RT y-flip too */
    int post_active = efx_render_post_active();
    float post_scale = 1.0f;
    int post_filter = EFX_FILTER_LINEAR;
    efx_render_render_scale(&post_scale, &post_filter);
    int scene_w = vw, scene_h = vh;
    uint64_t scene = 0;
    if (post_active) {
        scene_w = post_dim(vw, post_scale);
        scene_h = post_dim(vh, post_scale);
        scene = efx_render_post_scene_target(scene_w, scene_h);
    }
    int use_post = post_active && scene != 0;
    uint64_t default_surface = use_post ? scene : 0;

    int quad_verts = emit_quad_runs(records, runs, run_count, run_first,
                                    run_verts, use_post);

    /* F11: emit billboard and particle vertices after the quad batch (same
       vertex format; drawn with the depth-tested billboard pipeline) */
    if (!grow_int_pair(&P.rec_boff, &P.rec_bcnt, &P.rec_cap, count)) {
        return;
    }
    int *boff = P.rec_boff;
    int *bcnt = P.rec_bcnt;
    for (int i = 0; i < count; i++) {
        boff[i] = -1;
        bcnt[i] = 0;
    }
    int total = emit_billboards_and_particles(records, count, boff, bcnt,
                                              use_post, scene_w, scene_h,
                                              vw, vh, quad_verts);
    if (total < 0) {
        return;
    }
    upload_vertices(total);

    play_records(records, count, runs, run_count, run_first, run_verts, boff,
                 bcnt, use_post, scene_w, scene_h, vw, vh, default_surface);
}

void efx_pipeline_shutdown(void) {
    if (!P.installed) {
        return;
    }
    for (int i = 0; i < 3; i++) {
        sg_destroy_pipeline(P.quad_pip[i]);
        sg_destroy_pipeline(P.bill_pip[i]);
        sg_destroy_pipeline(P.mesh_pip[i]);
        sg_destroy_pipeline(P.mesh_pip_cw[i]);
    }
    for (int i = 0; i < POST_PROG_COUNT; i++) {
        sg_destroy_pipeline(P.post_pip[i]);
        sg_destroy_shader(P.post_shd[i]);
    }
    sg_destroy_sampler(P.smp);
    sg_destroy_sampler(P.smp_nearest);
    for (int w = 0; w < 3; w++) {
        for (int f = 0; f < 2; f++) {
            for (int m = 0; m < 2; m++) {
                if (P.tex_smp[w][f][m].id != SG_INVALID_ID) {
                    sg_destroy_sampler(P.tex_smp[w][f][m]);
                }
            }
        }
    }
    sg_destroy_buffer(P.vbuf);
    sg_destroy_buffer(P.post_vbuf);
    sg_destroy_shader(P.quad_shd);
    sg_destroy_shader(P.mesh_shd);
    free(P.scratch);
    free(P.run_first);
    free(P.run_verts);
    free(P.rec_boff);
    free(P.rec_bcnt);
    memset(&P, 0, sizeof(P));
}
