/*
 * Sokol implementation of the render-module GPU sink: canned 2D quad
 * shader + 3D mesh shader (sokol-shdc generated, ADR 0015/0021), blend
 * pipeline variants, dynamic quad batching and indexed mesh playback
 * with depth (design D1–D7, F3).
 */
#include "platform/pipeline.h"
#include "platform/backend.h"
#include "render/render.h"
#include "math/efx_math.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "sokol_gfx.h"

/* interleaved quad vertex: pos(2f) uv(2f) color(ub4n) = 20 bytes */
typedef struct {
    float x, y, u, v;
    uint8_t r, g, b, a;
} pipe_vertex;

/* interleaved mesh vertex: pos(3f) normal(3f) uv(2f) color(4f) = 48 bytes
 * (design D1: all attribute slots present, defaults filled at upload).
 * The full 4-element layout matches the shader input signature exactly;
 * D3D11 CreateInputLayout returns E_INVALIDARG for partial coverage. */
typedef struct {
    float x, y, z;
    float nx, ny, nz;
    float u, v;
    float r, g, b, a;
} pipe_mesh_vertex;

typedef struct {
    sg_image img;
    sg_view view;
} pipe_tex;

/* F5a offscreen render target: env-default color+depth attachments plus a
 * texture view over the color image (sampling a target = texture coercion,
 * design D1) */
typedef struct {
    int w, h;
    sg_image color, depth;
    sg_view color_att, depth_att, color_tex;
} pipe_rt;

typedef struct {
    sg_buffer vbuf, ibuf;
    int index_count; /* 0 = non-indexed (draw vertex count) */
    int vertex_count;
} pipe_mesh_surface;

typedef struct {
    int surface_count;
    pipe_mesh_surface *surfaces;
} pipe_mesh;

typedef struct {
    sg_shader quad_shd;
    sg_pipeline quad_pip[3];
    sg_shader mesh_shd;
    sg_pipeline mesh_pip[3];
    sg_sampler smp;
    sg_view white_view; /* engine white texture, used for absent F4b maps */
    sg_buffer vbuf;
    size_t vbuf_size;       /* bytes; grown on demand (dynamic quad batch) */
    pipe_vertex *scratch;
    int scratch_cap;
    int *run_first, *run_verts; /* per-run first vertex / vertex count */
    int run_cap;
    int installed;
    int depth_remap; /* D3D11/Metal: fold 0..1 depth range into MVP */
    sg_attachments default_atts; /* invalid id = swapchain (capture only) */
    /* view-projection cache: consecutive mesh records usually share the
       camera snapshot, so recompose only when it (or the aspect) changes */
    int pv_valid;
    efx_camera3d pv_cam;
    float pv_aspect;
    float pv[16];
} pipe_state;

static pipe_state P;

#define SOKOL_SHDC_IMPL
#include "shaders/quad.h" /* generated by sokol-shdc from shaders/quad.glsl (ADR 0021) */
#include "shaders/mesh.h" /* generated by sokol-shdc from shaders/mesh.glsl (ADR 0021) */

#include "sokol_glue.h" /* sglue_swapchain + sglue_environment (impl in platform.c) */

static void *pipe_create_texture(void *ud, int w, int h, const uint8_t *rgba) {
    (void)ud;
    pipe_tex *t = calloc(1, sizeof(pipe_tex));
    t->img = sg_make_image(&(sg_image_desc){
        .width = w,
        .height = h,
        .pixel_format = SG_PIXELFORMAT_RGBA8,
        .data = {.mip_levels[0] = {.ptr = rgba, .size = (size_t)w * h * 4}},
    });
    t->view = sg_make_view(&(sg_view_desc){
        .texture.image = t->img,
    });
    return t;
}

static void pipe_destroy_texture(void *ud, void *native) {
    (void)ud;
    pipe_tex *t = (pipe_tex *)native;
    if (t) {
        sg_destroy_view(t->view);
        sg_destroy_image(t->img);
        free(t);
    }
}

/* F5a: color image omits pixel_format/sample_count on purpose — sokol
 * defaults them from the environment (ADR 0025's env-default rule); the
 * depth image needs the environment's depth format explicitly */
static void *pipe_create_render_target(void *ud, int w, int h) {
    (void)ud;
    pipe_rt *t = calloc(1, sizeof(pipe_rt));
    if (!t) {
        return NULL;
    }
    t->w = w;
    t->h = h;
    sg_environment env = sglue_environment();
    t->color = sg_make_image(&(sg_image_desc){
        .width = w,
        .height = h,
        .usage = {.color_attachment = true},
    });
    t->depth = sg_make_image(&(sg_image_desc){
        .width = w,
        .height = h,
        .pixel_format = env.defaults.depth_format,
        .usage = {.depth_stencil_attachment = true},
    });
    if (t->color.id == SG_INVALID_ID || t->depth.id == SG_INVALID_ID) {
        if (t->color.id != SG_INVALID_ID) {
            sg_destroy_image(t->color);
        }
        if (t->depth.id != SG_INVALID_ID) {
            sg_destroy_image(t->depth);
        }
        free(t);
        return NULL;
    }
    t->color_att = sg_make_view(&(sg_view_desc){
        .color_attachment.image = t->color,
    });
    t->depth_att = sg_make_view(&(sg_view_desc){
        .depth_stencil_attachment.image = t->depth,
    });
    t->color_tex = sg_make_view(&(sg_view_desc){
        .texture.image = t->color,
    });
    return t;
}

static void pipe_destroy_render_target(void *ud, void *native) {
    (void)ud;
    pipe_rt *t = (pipe_rt *)native;
    if (t) {
        sg_destroy_view(t->color_att);
        sg_destroy_view(t->depth_att);
        sg_destroy_view(t->color_tex);
        sg_destroy_image(t->color);
        sg_destroy_image(t->depth);
        free(t);
    }
}

static void *pipe_create_mesh(void *ud, const efx_mesh_gpu_surface *surfs,
                              int count) {
    (void)ud;
    if (count < 1) {
        return NULL;
    }
    pipe_mesh *m = calloc(1, sizeof(pipe_mesh));
    if (!m) {
        return NULL;
    }
    m->surface_count = count;
    m->surfaces = calloc((size_t)count, sizeof(pipe_mesh_surface));
    if (!m->surfaces) {
        free(m);
        return NULL;
    }
    for (int i = 0; i < count; i++) {
        pipe_mesh_surface *d = &m->surfaces[i];
        d->vertex_count = surfs[i].vertex_count;
        d->index_count = surfs[i].index_count;
        d->vbuf = sg_make_buffer(&(sg_buffer_desc){
            .data = {.ptr = surfs[i].interleaved,
                     .size = (size_t)surfs[i].vertex_count *
                             sizeof(pipe_mesh_vertex)},
        });
        if (surfs[i].indices) {
            d->ibuf = sg_make_buffer(&(sg_buffer_desc){
                .usage = {.index_buffer = true},
                .data = {.ptr = surfs[i].indices,
                         .size = (size_t)surfs[i].index_count *
                                 sizeof(uint32_t)},
            });
        }
    }
    return m;
}

static void pipe_destroy_mesh(void *ud, void *native) {
    (void)ud;
    pipe_mesh *m = (pipe_mesh *)native;
    if (m) {
        for (int i = 0; i < m->surface_count; i++) {
            sg_destroy_buffer(m->surfaces[i].vbuf);
            sg_destroy_buffer(m->surfaces[i].ibuf);
        }
        free(m->surfaces);
        free(m);
    }
}

static uint32_t pack_color(const float c[4]) {
    uint32_t r = (uint32_t)(c[0] * 255.0f + 0.5f);
    uint32_t g = (uint32_t)(c[1] * 255.0f + 0.5f);
    uint32_t b = (uint32_t)(c[2] * 255.0f + 0.5f);
    uint32_t a = (uint32_t)(c[3] * 255.0f + 0.5f);
    return (a << 24) | (b << 16) | (g << 8) | r;
}

static pipe_vertex emit_vert(const efx_quad_record *r, int i) {
    /* corner i in strip order: TL, TR, BL, BR; local space is 0..w, 0..h */
    static const float lu[4] = {0, 1, 0, 1};
    static const float lv[4] = {0, 0, 1, 1};
    static const float su[4] = {0, 1, 0, 1};
    static const float sv[4] = {0, 0, 1, 1};
    pipe_vertex v;
    const uint32_t packed = pack_color(r->color);
    {
        float fx = r->m.a * lu[i] * r->w + r->m.c * lv[i] * r->h + r->m.tx;
        float fy = r->m.b * lu[i] * r->w + r->m.d * lv[i] * r->h + r->m.ty;
        v.x = 2.0f * fx / r->frame_w - 1.0f;
        v.y = 1.0f - 2.0f * fy / r->frame_h;
        v.u = (r->sx + su[i] * r->sw) / r->tw;
        v.v = (r->sy + sv[i] * r->sh) / r->th;
        v.r = (uint8_t)(packed & 0xff);
        v.g = (uint8_t)((packed >> 8) & 0xff);
        v.b = (uint8_t)((packed >> 16) & 0xff);
        v.a = (uint8_t)((packed >> 24) & 0xff);
    }
    return v;
}

static pipe_vertex *emit_quad(pipe_vertex *v, const efx_quad_record *r) {
    for (int i = 0; i < 4; i++) {
        *v++ = emit_vert(r, i);
    }
    return v;
}

static pipe_vertex *emit_quad_bridged(pipe_vertex *v, const efx_quad_record *r) {
    /* continue a strip: duplicate last vertex, then first vertex of the new
       quad twice, then the remaining three (two degenerate triangles) */
    v[0] = v[-1];
    v[1] = emit_vert(r, 0);
    v[2] = v[1];
    v += 3;
    for (int i = 1; i < 4; i++) {
        *v++ = emit_vert(r, i);
    }
    return v;
}


void efx_pipeline_install(void) {
    if (P.installed) {
        return;
    }
    memset(&P, 0, sizeof(P));

    P.quad_shd = sg_make_shader(quad_shader_desc(sg_query_backend()));
    P.mesh_shd = sg_make_shader(mesh_shader_desc(sg_query_backend()));

    static const sg_blend_state blends[3] = {
        /* alpha: src*sa + dst*(1-sa) */
        {.enabled = true,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA},
        /* additive: dst + src*sa */
        {.enabled = true,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE},
        /* subtractive: dst - src*sa */
        {.enabled = true,
         .op_rgb = SG_BLENDOP_SUBTRACT,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE,
         .op_alpha = SG_BLENDOP_SUBTRACT,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE},
    };

    for (int i = 0; i < 3; i++) {
        P.quad_pip[i] = sg_make_pipeline(&(sg_pipeline_desc){
            .shader = P.quad_shd,
            .primitive_type = SG_PRIMITIVETYPE_TRIANGLE_STRIP,
            .layout = {.buffers[0].stride = (int)sizeof(pipe_vertex),
                       .attrs = {[0] = {.format = SG_VERTEXFORMAT_FLOAT2},
                                 [1] = {.format = SG_VERTEXFORMAT_FLOAT2, .offset = 8},
                                 [2] = {.format = SG_VERTEXFORMAT_UBYTE4N, .offset = 16}}},
            /* color format: environment default (matches the swapchain
               and the capture attachments on every backend) */
            .colors[0] = {.blend = blends[i]},
            .depth = {.compare = SG_COMPAREFUNC_ALWAYS, .write_enabled = false},
            .cull_mode = SG_CULLMODE_NONE,
            .sample_count = 1,
        });
        /* mesh pipelines: indexed triangles, depth-tested and writing
           (design D4), backface culling on CCW front faces (design D6) */
        sg_pipeline_desc md = {
            .shader = P.mesh_shd,
            .primitive_type = SG_PRIMITIVETYPE_TRIANGLES,
            /* mesh surfaces always draw indexed; non-indexed surfaces get
               a synthesized identity index buffer at upload (render.c) */
            .index_type = SG_INDEXTYPE_UINT32,
            /* all four attribute slots are declared so the layout matches
               the shader input signature on every backend (D3D11
               CreateInputLayout rejects partial coverage); normal/uv are
               bound but unused until F4 reads them */
            .layout = {.buffers[0].stride = (int)sizeof(pipe_mesh_vertex),
                       .attrs = {[ATTR_mesh_a_pos] = {.format = SG_VERTEXFORMAT_FLOAT3, .offset = 0},
                                 [ATTR_mesh_a_normal] = {.format = SG_VERTEXFORMAT_FLOAT3, .offset = 12},
                                 [ATTR_mesh_a_uv] = {.format = SG_VERTEXFORMAT_FLOAT2, .offset = 24},
                                 [ATTR_mesh_a_color] = {.format = SG_VERTEXFORMAT_FLOAT4, .offset = 32}}},
            .colors[0] = {.blend = blends[i]},
            .depth = {.compare = SG_COMPAREFUNC_LESS_EQUAL,
                      .write_enabled = true},
            .cull_mode = SG_CULLMODE_BACK,
            .face_winding = SG_FACEWINDING_CCW,
            .sample_count = 1,
        };
        P.mesh_pip[i] = sg_make_pipeline(&md);
    }

    /* D3D11/Metal use a 0..1 depth range: fold the GL-style (-1..1)
       projection into clip space at playback (design D3/D4) */
    P.depth_remap = sg_query_features().origin_top_left ? 1 : 0;

    P.smp = sg_make_sampler(&(sg_sampler_desc){.min_filter = SG_FILTER_LINEAR,
                                               .mag_filter = SG_FILTER_LINEAR});
    P.vbuf_size = 256 * 1024;
    P.vbuf = sg_make_buffer(&(sg_buffer_desc){
        .size = P.vbuf_size,
        .usage = {.vertex_buffer = true, .dynamic_update = true},
    });
    P.installed = 1;

    static const efx_render_sink sink = {
        NULL, pipe_create_texture, pipe_destroy_texture,
        pipe_create_mesh, pipe_destroy_mesh, NULL,
        pipe_create_render_target, pipe_destroy_render_target,
    };
    efx_render_install_sink(&sink);
    uint64_t white = efx_render_white_texture(); /* engine-owned 1x1 white (D5) */
    pipe_tex *wt = (pipe_tex *)efx_render_texture_native(white);
    P.white_view = wt ? wt->view : (sg_view){0}; /* absent F4b maps fall back */
}

/* 3D camera + mesh playback (F3): per record, compose MVP from the
 * recorded camera and draw every surface in surface order (design
 * D3/D4/D7); equal-depth fragments resolve by record order because the
 * playback order is the record order */
static const float *view_projection(const efx_camera3d *cam, float aspect) {
    if (P.pv_valid && P.pv_aspect == aspect &&
        memcmp(&P.pv_cam, cam, sizeof(*cam)) == 0) {
        return P.pv;
    }
    float up[3] = {0, 1, 0};
    float view[16], proj[16];
    efx_math_look_at(view, cam->pos, cam->target, up);
    efx_math_perspective(proj, cam->fov, aspect, cam->near_z, cam->far_z);
    efx_math_mul(P.pv, proj, view);
    P.pv_cam = *cam;
    P.pv_aspect = aspect;
    P.pv_valid = 1;
    return P.pv;
}

/* pass-action builder (moved from platform.c: playback owns its passes) */
static sg_pass_action pipe_pass_action(const float clear[4]) {
    sg_pass_action pa;
    memset(&pa, 0, sizeof(pa));
    pa.colors[0].load_action = SG_LOADACTION_CLEAR;
    pa.colors[0].clear_value = (sg_color){clear[0], clear[1], clear[2], clear[3]};
    /* F3 depth: cleared to far (1.0) each pass (design D4) */
    pa.depth.load_action = SG_LOADACTION_CLEAR;
    pa.depth.clear_value = 1.0f;
    return pa;
}

/* the default segment renders into the swapchain, or into the capture
   attachments when the platform overrides them (Metal goldens) */
static void begin_default_pass(const float clear[4]) {
    if (P.default_atts.colors[0].id != SG_INVALID_ID) {
        sg_begin_pass(&(sg_pass){
            .action = pipe_pass_action(clear),
            .attachments = P.default_atts,
        });
    } else {
        sg_begin_pass(&(sg_pass){
            .action = pipe_pass_action(clear),
            .swapchain = sglue_swapchain(),
        });
    }
}

void efx_pipeline_set_default_attachments(sg_attachments atts) {
    P.default_atts = atts;
}

/* texture coercion (F5a design D1): a sampling handle resolves through the
 * texture registry first, then the render-target registry */
static sg_view view_for_handle(uint64_t h) {
    pipe_tex *t = (pipe_tex *)efx_render_texture_native(h);
    if (t) {
        return t->view;
    }
    pipe_rt *rt = (pipe_rt *)efx_render_target_native(h);
    return rt ? rt->color_tex : (sg_view){0};
}

static void play_mesh_record(const efx_mesh_record *mr, float aspect) {
    pipe_mesh *m = (pipe_mesh *)efx_render_mesh_native(mr->mesh);
    if (!m) {
        return;
    }
    float mvp[16];
    efx_math_mul(mvp, view_projection(&mr->camera, aspect), mr->transform);
    if (P.depth_remap) {
        /* row 2 of the clip matrix: z' = 0.5*z_clip + 0.5*w_clip maps the
           GL-style (-1..1) range onto the D3D11/Metal (0..1) range;
           monotonic, so depth comparisons and ties are unchanged. Row 3
           carries the perspective w in every column (not just the
           translation), so the fold must cover all four columns
           (ADR 0025). */
        for (int c = 0; c < 4; c++) {
            mvp[c * 4 + 2] = 0.5f * mvp[c * 4 + 2] + 0.5f * mvp[c * 4 + 3];
        }
    }

    vs_params_t vs;
    memcpy(vs.mvp, mvp, sizeof(mvp));
    memcpy(vs.model, mr->transform, sizeof(vs.model));
    efx_math_normal_matrix(vs.normal_mat, mr->transform);

    fs_params_t fs;
    memset(&fs, 0, sizeof(fs));
    fs.tint[0] = mr->color[0];
    fs.tint[1] = mr->color[1];
    fs.tint[2] = mr->color[2];
    fs.tint[3] = mr->color[3];
    fs.camera_pos[0] = mr->camera.pos[0];
    fs.camera_pos[1] = mr->camera.pos[1];
    fs.camera_pos[2] = mr->camera.pos[2];
    for (int i = 0; i < EFX_MAX_POINT_LIGHTS; i++) {
        const efx_point_light *p = &mr->lights.points[i];
        if (!p->enabled) {
            continue;
        }
        fs.point_pos[i][0] = p->pos[0];
        fs.point_pos[i][1] = p->pos[1];
        fs.point_pos[i][2] = p->pos[2];
        fs.point_pos[i][3] = p->range;
        fs.point_color[i][0] = p->color[0];
        fs.point_color[i][1] = p->color[1];
        fs.point_color[i][2] = p->color[2];
        fs.point_color[i][3] = 1.0f;
    }
    if (mr->lights.directional.enabled) {
        fs.dir_dir[0] = mr->lights.directional.dir[0];
        fs.dir_dir[1] = mr->lights.directional.dir[1];
        fs.dir_dir[2] = mr->lights.directional.dir[2];
        fs.dir_dir[3] = 1.0f;
        fs.dir_color[0] = mr->lights.directional.color[0];
        fs.dir_color[1] = mr->lights.directional.color[1];
        fs.dir_color[2] = mr->lights.directional.color[2];
    }

    sg_apply_pipeline(P.mesh_pip[mr->blend]);
    sg_apply_uniforms(UB_vs_params, &(sg_range){.ptr = &vs, .size = sizeof(vs)});
    uint64_t white = efx_render_white_texture(); /* absent-map fallback (D3) */
    pipe_tex *white_tex = (pipe_tex *)efx_render_texture_native(white);
    sg_view white_view = white_tex ? white_tex->view : P.white_view;
    for (int i = 0; i < m->surface_count; i++) {
        pipe_mesh_surface *s = &m->surfaces[i];
        if (!s->index_count) {
            continue;
        }
        efx_material mat;
        efx_render_mesh_surface_material(mr->mesh, i, &mat);
        memcpy(fs.ambient, mat.ambient, sizeof(fs.ambient));
        memcpy(fs.diffuse, mat.diffuse, sizeof(fs.diffuse));
        memcpy(fs.specular, mat.specular, sizeof(fs.specular));
        memcpy(fs.emissive, mat.emissive, sizeof(fs.emissive));
        fs.mat_params[0] = mat.shininess;

        /* F4b D3: bind all five maps; absent ones fall back to the engine
           white texture (color maps sample (1,1,1,1); the mask samples
           alpha 1, so it never discards). One shared sampler for all. */
        uint64_t maps[5] = {mat.ambient_map, mat.diffuse_map, mat.specular_map,
                            mat.emissive_map, mat.alpha_mask};
        sg_bindings bnd = {0};
        bnd.vertex_buffers[0] = s->vbuf;
        bnd.index_buffer = s->ibuf;
        for (int k = 0; k < 5; k++) {
            sg_view map_view = view_for_handle(maps[k]);
            bnd.views[k] = map_view.id != SG_INVALID_ID ? map_view : white_view;
            bnd.samplers[k] = P.smp;
        }
        sg_apply_bindings(&bnd);
        /* documented order: pipeline -> bindings -> uniforms -> draw */
        sg_apply_uniforms(UB_fs_params,
                          &(sg_range){.ptr = &fs, .size = sizeof(fs)});
        sg_draw(0, s->index_count, 1);
    }
}

void efx_pipeline_play(void) {
    if (!P.installed) {
        return;
    }
    int count = 0;
    const efx_record *records = efx_render_records(&count);
    int run_count = 0;
    const efx_draw_run *runs = count > 0 ? efx_render_runs(&run_count) : NULL;
    if (run_count > 0 && !runs) {
        return;
    }

    int vw = 0, vh = 0;
    efx_render_viewport(&vw, &vh);

    /* quad scratch sizing: only the quad records are emitted */
    int quad_count = 0;
    for (int i = 0; i < count; i++) {
        if (records[i].type == EFX_RECORD_QUAD) {
            quad_count++;
        }
    }
    if (quad_count > 0) {
        int cap = quad_count * 6 + 4;
        if (cap > P.scratch_cap) {
            pipe_vertex *grown = realloc(P.scratch, (size_t)cap * sizeof(pipe_vertex));
            if (!grown) {
                return;
            }
            P.scratch = grown;
            P.scratch_cap = cap;
        }
    }

    /* F2 playback: emit ALL quad runs into one dynamic-buffer update
       (multiple updates per frame are unreliable on Metal/D3D11), then
       interleave run draws and mesh records in record order */
    if (run_count > P.run_cap) {
        int cap = P.run_cap ? P.run_cap : 64;
        while (cap < run_count) {
            cap *= 2;
        }
        int *first = realloc(P.run_first, (size_t)cap * sizeof(int));
        int *verts = realloc(P.run_verts, (size_t)cap * sizeof(int));
        if (first) P.run_first = first;
        if (verts) P.run_verts = verts;
        if (!first || !verts) {
            return;
        }
        P.run_cap = cap;
    }
    int *run_first = P.run_first;
    int *run_verts = P.run_verts;
    pipe_vertex *v = P.scratch;
    for (int ri = 0; ri < run_count; ri++) {
        run_first[ri] = (int)(v - P.scratch);
        int start = (int)(v - P.scratch);
        for (int q = 0; q < runs[ri].count; q++) {
            if (q > 0) {
                v = emit_quad_bridged(v, &records[runs[ri].start + q].u.quad);
            } else {
                v = emit_quad(v, &records[runs[ri].start + q].u.quad);
            }
        }
        run_verts[ri] = (int)(v - P.scratch) - start;
    }
    int vcount = (int)(v - P.scratch);
    if (vcount > 0) {
        size_t bytes = (size_t)vcount * sizeof(pipe_vertex);
        if (bytes > P.vbuf_size) {
            /* sokol buffers are fixed-size: replace with a larger one
               (updated once per frame, so a fresh buffer is safe here) */
            size_t size = P.vbuf_size;
            while (size < bytes) {
                size *= 2;
            }
            sg_destroy_buffer(P.vbuf);
            P.vbuf = sg_make_buffer(&(sg_buffer_desc){
                .size = size,
                .usage = {.vertex_buffer = true, .dynamic_update = true},
            });
            P.vbuf_size = size;
        }
        sg_update_buffer(P.vbuf, &(sg_range){.ptr = P.scratch, .size = bytes});
    }

    /* pass management (F5a): the default pass opens eagerly (clear-only
       frames render exactly as before); BEGIN/END control records switch
       between the default surface and render-target attachments */
    float frame_clear[4];
    efx_render_clear_color(frame_clear);
    int cur_w = vw, cur_h = vh;
    begin_default_pass(frame_clear);
    int run_i = 0;
    for (int i = 0; i < count; i++) {
        const efx_record *r = &records[i];
        if (r->type == EFX_RECORD_BEGIN_TARGET) {
            sg_end_pass();
            pipe_rt *rt =
                (pipe_rt *)efx_render_target_native(r->u.begin_target.target);
            if (rt) {
                sg_begin_pass(&(sg_pass){
                    .action = pipe_pass_action(r->u.begin_target.clear),
                    .attachments = {.colors[0] = rt->color_att,
                                    .depth_stencil = rt->depth_att},
                });
                cur_w = rt->w;
                cur_h = rt->h;
            } else {
                /* unreachable when validation holds: fall back to default */
                begin_default_pass(frame_clear);
                cur_w = vw;
                cur_h = vh;
            }
            continue;
        }
        if (r->type == EFX_RECORD_END_TARGET) {
            sg_end_pass();
            begin_default_pass(frame_clear);
            cur_w = vw;
            cur_h = vh;
            continue;
        }
        float aspect =
            (cur_w > 0 && cur_h > 0) ? (float)cur_w / (float)cur_h : 4.0f / 3.0f;
        if (r->type == EFX_RECORD_QUAD) {
            if (run_i < run_count && runs[run_i].start == i) {
                sg_apply_pipeline(P.quad_pip[runs[run_i].blend]);
                sg_bindings bnd = {0};
                bnd.vertex_buffers[0] = P.vbuf;
                sg_view view = view_for_handle(runs[run_i].texture);
                if (view.id != SG_INVALID_ID) {
                    bnd.views[0] = view;
                    bnd.samplers[0] = P.smp;
                    sg_apply_bindings(&bnd);
                    sg_draw(run_first[run_i], run_verts[run_i], 1);
                }
                run_i++;
                i += runs[run_i - 1].count - 1;
            }
        } else if (r->type == EFX_RECORD_MESH) {
            play_mesh_record(&r->u.mesh, aspect);
        }
    }
    sg_end_pass();
}

void efx_pipeline_shutdown(void) {
    if (!P.installed) {
        return;
    }
    for (int i = 0; i < 3; i++) {
        sg_destroy_pipeline(P.quad_pip[i]);
        sg_destroy_pipeline(P.mesh_pip[i]);
    }
    sg_destroy_sampler(P.smp);
    sg_destroy_buffer(P.vbuf);
    sg_destroy_shader(P.quad_shd);
    sg_destroy_shader(P.mesh_shd);
    free(P.scratch);
    free(P.run_first);
    free(P.run_verts);
    memset(&P, 0, sizeof(P));
}
