/*
 * Sokol implementation of the render-module GPU sink: canned 2D quad
 * shader + 3D mesh shader (sokol-shdc generated, ADR 0015/0021), blend
 * pipeline variants, dynamic quad batching and indexed mesh playback
 * with depth (design D1–D7, F3).
 */
#include "platform/pipeline.h"
#include "platform/backend.h"
#include "render/render.h"
#include "math/efx_math.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "sokol_gfx.h"

/* interleaved quad vertex: pos(2f) uv(2f) color(ub4n) = 20 bytes */
typedef struct {
    float x, y, u, v;
    uint8_t r, g, b, a;
} pipe_vertex;

/* interleaved mesh vertex: pos(3f) normal(3f) uv(2f) color(4f) = 48 bytes
 * (design D1: all attribute slots present, defaults filled at upload).
 * The full 4-element layout matches the shader input signature exactly;
 * D3D11 CreateInputLayout returns E_INVALIDARG for partial coverage. */
typedef struct {
    float x, y, z;
    float nx, ny, nz;
    float u, v;
    float r, g, b, a;
} pipe_mesh_vertex;

typedef struct {
    sg_image img;
    sg_view view;
    int wrap, filter; /* F6b per-texture sampler state */
    int mipmaps;      /* F6e: image carries a generated mip chain */
} pipe_tex;

/* F5a offscreen render target: env-default color+depth attachments plus a
 * texture view over the color image (sampling a target = texture coercion,
 * design D1) */
typedef struct {
    int w, h;
    sg_image color, depth;
    sg_view color_att, depth_att, color_tex;
} pipe_rt;

typedef struct {
    sg_buffer vbuf, ibuf;
    int index_count; /* 0 = non-indexed (draw vertex count) */
    int vertex_count;
} pipe_mesh_surface;

typedef struct {
    int surface_count;
    pipe_mesh_surface *surfaces;
} pipe_mesh;

typedef struct {
    sg_shader quad_shd;
    sg_pipeline quad_pip[3];
    sg_shader mesh_shd;
    sg_pipeline mesh_pip[3];
    sg_pipeline mesh_pip_cw[3]; /* GL-family RT passes: projection y-flip
                                   mirrors winding (F5a) */
    /* F5b post passes: one shader + pipeline per pass type (uniform-driven,
       no permutations) */
    sg_shader post_shd[6];
    sg_pipeline post_pip[6];
    sg_sampler smp;
    sg_sampler smp_nearest; /* render-scale nearest blit */
    sg_sampler tex_smp[3][2][2]; /* F6b/F6e per-texture samplers, cached by
                                    (wrap, filter, mipmaps) */
    sg_view white_view; /* engine white texture, used for absent F4b maps */
    sg_buffer vbuf;
    size_t vbuf_size;       /* bytes; grown on demand (dynamic quad batch) */
    sg_buffer post_vbuf;    /* static fullscreen quad for post passes */
    pipe_vertex *scratch;
    int scratch_cap;
    int *run_first, *run_verts; /* per-run first vertex / vertex count */
    int run_cap;
    int installed;
    int depth_remap; /* D3D11/Metal: fold 0..1 depth range into MVP */
    int rt_flip;     /* GL-family: flip y when rendering into RTs (F5a) */
    sg_attachments default_atts; /* invalid id = swapchain (capture only) */
    /* view-projection cache: consecutive mesh records usually share the
       camera snapshot, so recompose only when it (or the aspect) changes */
    int pv_valid;
    efx_camera3d pv_cam;
    float pv_aspect;
    int pv_flip;
    float pv[16];
} pipe_state;

static pipe_state P;

#define SOKOL_SHDC_IMPL
#include "shaders/quad.h" /* generated by sokol-shdc from shaders/quad.glsl (ADR 0021) */
#include "shaders/mesh.h" /* generated by sokol-shdc from shaders/mesh.glsl (ADR 0021) */
#include "shaders/post.h" /* generated by sokol-shdc from shaders/post.glsl (F5b) */

/* post pass programs, indexed by POST_* */
enum {
    POST_COLOR = 0,
    POST_BLUR,
    POST_BRIGHT,
    POST_MIX,
    POST_COMPOSITE,
    POST_COPY,
    POST_PROG_COUNT
};

/* fullscreen post vertex: NDC pos(2f) + uv(2f) */
typedef struct {
    float x, y, u, v;
} post_vertex;

#include "sokol_glue.h" /* sglue_swapchain + sglue_environment (impl in platform.c) */

/* F6e: number of mip levels for a full chain down to 1x1, driven by the
 * larger dimension (NPOT levels floor each step: max(1, n/2)) */
static int mip_level_count(int w, int h) {
    int n = w > h ? w : h;
    int count = 1;
    while (n > 1) {
        n >>= 1;
        count++;
    }
    return count;
}

/* F6e: 2x2 box-filter the chain on the CPU (deterministic across backends).
 * Level 0 aliases the caller's pixels; levels 1.. fill owned pointers that
 * the caller frees once sg_make_image has copied them. */
static void build_mip_chain(int w, int h, int levels, const uint8_t *rgba,
                            sg_image_data *data, uint8_t **owned) {
    data->mip_levels[0].ptr = rgba;
    data->mip_levels[0].size = (size_t)w * h * 4;
    const uint8_t *src = rgba;
    int cw = w, ch = h;
    for (int l = 1; l < levels; l++) {
        int nw = cw > 1 ? cw / 2 : 1;
        int nh = ch > 1 ? ch / 2 : 1;
        uint8_t *dst = malloc((size_t)nw * nh * 4);
        if (!dst) {
            owned[l] = NULL;
            return;
        }
        for (int y = 0; y < nh; y++) {
            for (int x = 0; x < nw; x++) {
                for (int c = 0; c < 4; c++) {
                    int sum = 0, cnt = 0;
                    for (int yy = y * 2; yy <= y * 2 + 1; yy++) {
                        if (yy >= ch) break;
                        for (int xx = x * 2; xx <= x * 2 + 1; xx++) {
                            if (xx >= cw) break;
                            sum += src[((size_t)yy * cw + xx) * 4 + c];
                            cnt++;
                        }
                    }
                    dst[((size_t)y * nw + x) * 4 + c] =
                        (uint8_t)((sum + cnt / 2) / cnt);
                }
            }
        }
        data->mip_levels[l].ptr = dst;
        data->mip_levels[l].size = (size_t)nw * nh * 4;
        owned[l] = dst;
        src = dst;
        cw = nw;
        ch = nh;
    }
}

static void *pipe_create_texture(void *ud, int w, int h, const uint8_t *rgba,
                                 int wrap, int filter, int mipmaps) {
    (void)ud;
    pipe_tex *t = calloc(1, sizeof(pipe_tex));
    if (!t) {
        return NULL;
    }
    sg_image_data data;
    memset(&data, 0, sizeof(data));
    uint8_t *owned[SG_MAX_MIPMAPS];
    memset(owned, 0, sizeof(owned));
    int levels = 1;
    if (mipmaps && rgba && (w > 1 || h > 1)) {
        levels = mip_level_count(w, h);
        if (levels > SG_MAX_MIPMAPS) {
            levels = SG_MAX_MIPMAPS;
        }
        build_mip_chain(w, h, levels, rgba, &data, owned);
        /* a failed level allocation degrades to the levels built so far */
        for (int l = 1; l < levels; l++) {
            if (!owned[l]) {
                levels = l;
                break;
            }
        }
        if (levels < 1) {
            levels = 1;
        }
    } else {
        data.mip_levels[0].ptr = rgba;
        data.mip_levels[0].size = (size_t)w * h * 4;
    }
    t->img = sg_make_image(&(sg_image_desc){
        .width = w,
        .height = h,
        .num_mipmaps = levels,
        .pixel_format = SG_PIXELFORMAT_RGBA8,
        .data = data,
    });
    for (int l = 1; l < levels; l++) {
        free(owned[l]);
    }
    t->view = sg_make_view(&(sg_view_desc){
        .texture.image = t->img,
    });
    t->wrap = wrap;
    t->filter = filter;
    t->mipmaps = levels > 1 ? 1 : 0;
    return t;
}

static void pipe_destroy_texture(void *ud, void *native) {
    (void)ud;
    pipe_tex *t = (pipe_tex *)native;
    if (t) {
        sg_destroy_view(t->view);
        sg_destroy_image(t->img);
        free(t);
    }
}

/* F5a: color image omits pixel_format/sample_count on purpose — sokol
 * defaults them from the environment (ADR 0025's env-default rule); the
 * depth image needs the environment's depth format explicitly */
static void *pipe_create_render_target(void *ud, int w, int h) {
    (void)ud;
    pipe_rt *t = calloc(1, sizeof(pipe_rt));
    if (!t) {
        return NULL;
    }
    t->w = w;
    t->h = h;
    sg_environment env = sglue_environment();
    t->color = sg_make_image(&(sg_image_desc){
        .width = w,
        .height = h,
        .usage = {.color_attachment = true},
    });
    t->depth = sg_make_image(&(sg_image_desc){
        .width = w,
        .height = h,
        .pixel_format = env.defaults.depth_format,
        .usage = {.depth_stencil_attachment = true},
    });
    if (t->color.id == SG_INVALID_ID || t->depth.id == SG_INVALID_ID) {
        if (t->color.id != SG_INVALID_ID) {
            sg_destroy_image(t->color);
        }
        if (t->depth.id != SG_INVALID_ID) {
            sg_destroy_image(t->depth);
        }
        free(t);
        return NULL;
    }
    t->color_att = sg_make_view(&(sg_view_desc){
        .color_attachment.image = t->color,
    });
    t->depth_att = sg_make_view(&(sg_view_desc){
        .depth_stencil_attachment.image = t->depth,
    });
    t->color_tex = sg_make_view(&(sg_view_desc){
        .texture.image = t->color,
    });
    return t;
}

static void pipe_destroy_render_target(void *ud, void *native) {
    (void)ud;
    pipe_rt *t = (pipe_rt *)native;
    if (t) {
        sg_destroy_view(t->color_att);
        sg_destroy_view(t->depth_att);
        sg_destroy_view(t->color_tex);
        sg_destroy_image(t->color);
        sg_destroy_image(t->depth);
        free(t);
    }
}

static void *pipe_create_mesh(void *ud, const efx_mesh_gpu_surface *surfs,
                              int count) {
    (void)ud;
    if (count < 1) {
        return NULL;
    }
    pipe_mesh *m = calloc(1, sizeof(pipe_mesh));
    if (!m) {
        return NULL;
    }
    m->surface_count = count;
    m->surfaces = calloc((size_t)count, sizeof(pipe_mesh_surface));
    if (!m->surfaces) {
        free(m);
        return NULL;
    }
    for (int i = 0; i < count; i++) {
        pipe_mesh_surface *d = &m->surfaces[i];
        d->vertex_count = surfs[i].vertex_count;
        d->index_count = surfs[i].index_count;
        d->vbuf = sg_make_buffer(&(sg_buffer_desc){
            .data = {.ptr = surfs[i].interleaved,
                     .size = (size_t)surfs[i].vertex_count *
                             sizeof(pipe_mesh_vertex)},
        });
        if (surfs[i].indices) {
            d->ibuf = sg_make_buffer(&(sg_buffer_desc){
                .usage = {.index_buffer = true},
                .data = {.ptr = surfs[i].indices,
                         .size = (size_t)surfs[i].index_count *
                                 sizeof(uint32_t)},
            });
        }
    }
    return m;
}

static void pipe_destroy_mesh(void *ud, void *native) {
    (void)ud;
    pipe_mesh *m = (pipe_mesh *)native;
    if (m) {
        for (int i = 0; i < m->surface_count; i++) {
            sg_destroy_buffer(m->surfaces[i].vbuf);
            sg_destroy_buffer(m->surfaces[i].ibuf);
        }
        free(m->surfaces);
        free(m);
    }
}

static uint32_t pack_color(const float c[4]) {
    uint32_t r = (uint32_t)(c[0] * 255.0f + 0.5f);
    uint32_t g = (uint32_t)(c[1] * 255.0f + 0.5f);
    uint32_t b = (uint32_t)(c[2] * 255.0f + 0.5f);
    uint32_t a = (uint32_t)(c[3] * 255.0f + 0.5f);
    return (a << 24) | (b << 16) | (g << 8) | r;
}

static pipe_vertex emit_vert(const efx_quad_record *r, int i, int flip_y) {
    /* corner i in strip order: TL, TR, BL, BR; local space is 0..w, 0..h */
    static const float lu[4] = {0, 1, 0, 1};
    static const float lv[4] = {0, 0, 1, 1};
    static const float su[4] = {0, 1, 0, 1};
    static const float sv[4] = {0, 0, 1, 1};
    pipe_vertex v;
    const uint32_t packed = pack_color(r->color);
    {
        float fx = r->m.a * lu[i] * r->w + r->m.c * lv[i] * r->h + r->m.tx;
        float fy = r->m.b * lu[i] * r->w + r->m.d * lv[i] * r->h + r->m.ty;
        v.x = 2.0f * fx / r->frame_w - 1.0f;
        v.y = 1.0f - 2.0f * fy / r->frame_h;
        /* GL-family backends land offscreen render output top-at-v=1,
           while sokol's image convention (and every upload) is top-at-v=0
           (ADR 0028: origin conventions are engine-owned). Rendering INTO
           a render target is flipped here so sampled content is upright
           on every backend; the default framebuffer is unaffected. */
        if (flip_y) {
            v.y = -v.y;
        }
        v.u = (r->sx + su[i] * r->sw) / r->tw;
        v.v = (r->sy + sv[i] * r->sh) / r->th;
        v.r = (uint8_t)(packed & 0xff);
        v.g = (uint8_t)((packed >> 8) & 0xff);
        v.b = (uint8_t)((packed >> 16) & 0xff);
        v.a = (uint8_t)((packed >> 24) & 0xff);
    }
    return v;
}

static pipe_vertex *emit_quad(pipe_vertex *v, const efx_quad_record *r,
                              int flip_y) {
    for (int i = 0; i < 4; i++) {
        *v++ = emit_vert(r, i, flip_y);
    }
    return v;
}

static pipe_vertex *emit_quad_bridged(pipe_vertex *v, const efx_quad_record *r,
                                      int flip_y) {
    /* continue a strip: duplicate last vertex, then first vertex of the new
       quad twice, then the remaining three (two degenerate triangles) */
    v[0] = v[-1];
    v[1] = emit_vert(r, 0, flip_y);
    v[2] = v[1];
    v += 3;
    for (int i = 1; i < 4; i++) {
        *v++ = emit_vert(r, i, flip_y);
    }
    return v;
}


void efx_pipeline_install(void) {
    if (P.installed) {
        return;
    }
    memset(&P, 0, sizeof(P));

    P.quad_shd = sg_make_shader(quad_shader_desc(sg_query_backend()));
    P.mesh_shd = sg_make_shader(mesh_shader_desc(sg_query_backend()));

    static const sg_blend_state blends[3] = {
        /* alpha: src*sa + dst*(1-sa) */
        {.enabled = true,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA},
        /* additive: dst + src*sa */
        {.enabled = true,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE},
        /* subtractive: dst - src*sa */
        {.enabled = true,
         .op_rgb = SG_BLENDOP_SUBTRACT,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE,
         .op_alpha = SG_BLENDOP_SUBTRACT,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE},
    };

    for (int i = 0; i < 3; i++) {
        P.quad_pip[i] = sg_make_pipeline(&(sg_pipeline_desc){
            .shader = P.quad_shd,
            .primitive_type = SG_PRIMITIVETYPE_TRIANGLE_STRIP,
            .layout = {.buffers[0].stride = (int)sizeof(pipe_vertex),
                       .attrs = {[0] = {.format = SG_VERTEXFORMAT_FLOAT2},
                                 [1] = {.format = SG_VERTEXFORMAT_FLOAT2, .offset = 8},
                                 [2] = {.format = SG_VERTEXFORMAT_UBYTE4N, .offset = 16}}},
            /* color format: environment default (matches the swapchain
               and the capture attachments on every backend) */
            .colors[0] = {.blend = blends[i]},
            .depth = {.compare = SG_COMPAREFUNC_ALWAYS, .write_enabled = false},
            .cull_mode = SG_CULLMODE_NONE,
            .sample_count = 1,
        });
        /* mesh pipelines: indexed triangles, depth-tested and writing
           (design D4), backface culling on CCW front faces (design D6) */
        sg_pipeline_desc md = {
            .shader = P.mesh_shd,
            .primitive_type = SG_PRIMITIVETYPE_TRIANGLES,
            /* mesh surfaces always draw indexed; non-indexed surfaces get
               a synthesized identity index buffer at upload (render.c) */
            .index_type = SG_INDEXTYPE_UINT32,
            /* all four attribute slots are declared so the layout matches
               the shader input signature on every backend (D3D11
               CreateInputLayout rejects partial coverage); normal/uv are
               bound but unused until F4 reads them */
            .layout = {.buffers[0].stride = (int)sizeof(pipe_mesh_vertex),
                       .attrs = {[ATTR_mesh_a_pos] = {.format = SG_VERTEXFORMAT_FLOAT3, .offset = 0},
                                 [ATTR_mesh_a_normal] = {.format = SG_VERTEXFORMAT_FLOAT3, .offset = 12},
                                 [ATTR_mesh_a_uv] = {.format = SG_VERTEXFORMAT_FLOAT2, .offset = 24},
                                 [ATTR_mesh_a_color] = {.format = SG_VERTEXFORMAT_FLOAT4, .offset = 32}}},
            .colors[0] = {.blend = blends[i]},
            .depth = {.compare = SG_COMPAREFUNC_LESS_EQUAL,
                      .write_enabled = true},
            .cull_mode = SG_CULLMODE_BACK,
            .face_winding = SG_FACEWINDING_CCW,
            .sample_count = 1,
        };
        P.mesh_pip[i] = sg_make_pipeline(&md);
        md.face_winding = SG_FACEWINDING_CW;
        P.mesh_pip_cw[i] = sg_make_pipeline(&md);
    }

    /* D3D11/Metal use a 0..1 depth range: fold the GL-style (-1..1)
       projection into clip space at playback (design D3/D4) */
    P.depth_remap = sg_query_features().origin_top_left ? 1 : 0;
    /* GL-family backends land offscreen render output top-at-v=1 (ADR
       0028): rendering INTO a render target flips y engine-side */
    P.rt_flip = P.depth_remap ? 0 : 1;

    P.smp = sg_make_sampler(&(sg_sampler_desc){.min_filter = SG_FILTER_LINEAR,
                                               .mag_filter = SG_FILTER_LINEAR});
    P.smp_nearest = sg_make_sampler(&(sg_sampler_desc){
        .min_filter = SG_FILTER_NEAREST, .mag_filter = SG_FILTER_NEAREST});
    P.vbuf_size = 256 * 1024;
    P.vbuf = sg_make_buffer(&(sg_buffer_desc){
        .size = P.vbuf_size,
        .usage = {.vertex_buffer = true, .dynamic_update = true},
    });

    /* F5b post passes: a static fullscreen quad (triangle strip, top-left
       uv origin) and one uniform-driven pipeline per pass type */
    static const post_vertex post_quad[4] = {
        {-1.0f, 1.0f, 0.0f, 0.0f},
        {1.0f, 1.0f, 1.0f, 0.0f},
        {-1.0f, -1.0f, 0.0f, 1.0f},
        {1.0f, -1.0f, 1.0f, 1.0f},
    };
    P.post_vbuf = sg_make_buffer(&(sg_buffer_desc){
        .data = {.ptr = post_quad, .size = sizeof(post_quad)},
    });
    P.post_shd[POST_COLOR] = sg_make_shader(post_color_shader_desc(sg_query_backend()));
    P.post_shd[POST_BLUR] = sg_make_shader(post_blur_shader_desc(sg_query_backend()));
    P.post_shd[POST_BRIGHT] = sg_make_shader(post_bright_shader_desc(sg_query_backend()));
    P.post_shd[POST_MIX] = sg_make_shader(post_mix_shader_desc(sg_query_backend()));
    P.post_shd[POST_COMPOSITE] = sg_make_shader(post_composite_shader_desc(sg_query_backend()));
    P.post_shd[POST_COPY] = sg_make_shader(post_copy_shader_desc(sg_query_backend()));
    for (int i = 0; i < POST_PROG_COUNT; i++) {
        P.post_pip[i] = sg_make_pipeline(&(sg_pipeline_desc){
            .shader = P.post_shd[i],
            .primitive_type = SG_PRIMITIVETYPE_TRIANGLE_STRIP,
            .layout = {.buffers[0].stride = (int)sizeof(post_vertex),
                       .attrs = {[0] = {.format = SG_VERTEXFORMAT_FLOAT2},
                                 [1] = {.format = SG_VERTEXFORMAT_FLOAT2, .offset = 8}}},
            .depth = {.compare = SG_COMPAREFUNC_ALWAYS, .write_enabled = false},
            .cull_mode = SG_CULLMODE_NONE,
            .sample_count = 1,
        });
    }
    P.installed = 1;

    static const efx_render_sink sink = {
        NULL, pipe_create_texture, pipe_destroy_texture,
        pipe_create_mesh, pipe_destroy_mesh, NULL,
        pipe_create_render_target, pipe_destroy_render_target,
    };
    efx_render_install_sink(&sink);
    uint64_t white = efx_render_white_texture(); /* engine-owned 1x1 white (D5) */
    pipe_tex *wt = (pipe_tex *)efx_render_texture_native(white);
    P.white_view = wt ? wt->view : (sg_view){0}; /* absent F4b maps fall back */
}

/* 3D camera + mesh playback (F3): per record, compose MVP from the
 * recorded camera and draw every surface in surface order (design
 * D3/D4/D7); equal-depth fragments resolve by record order because the
 * playback order is the record order */
static const float *view_projection(const efx_camera3d *cam, float aspect,
                                    int flip) {
    if (P.pv_valid && P.pv_aspect == aspect && P.pv_flip == flip &&
        memcmp(&P.pv_cam, cam, sizeof(*cam)) == 0) {
        return P.pv;
    }
    float up[3] = {0, 1, 0};
    float view[16], proj[16];
    efx_math_look_at(view, cam->pos, cam->target, up);
    efx_math_perspective(proj, cam->fov, aspect, cam->near_z, cam->far_z);
    efx_math_mul(P.pv, proj, view);
    if (flip) {
        /* GL-family RT passes: flip y so the attachment lands in sokol's
           top-at-v=0 image convention (F5a, ADR 0028); winding is
           compensated by the CW pipeline variants */
        for (int c = 0; c < 4; c++) {
            P.pv[c * 4 + 1] = -P.pv[c * 4 + 1];
        }
    }
    P.pv_cam = *cam;
    P.pv_aspect = aspect;
    P.pv_flip = flip;
    P.pv_valid = 1;
    return P.pv;
}

/* pass-action builder (moved from platform.c: playback owns its passes) */
static sg_pass_action pipe_pass_action(const float clear[4]) {
    sg_pass_action pa;
    memset(&pa, 0, sizeof(pa));
    pa.colors[0].load_action = SG_LOADACTION_CLEAR;
    pa.colors[0].clear_value = (sg_color){clear[0], clear[1], clear[2], clear[3]};
    /* F3 depth: cleared to far (1.0) each pass (design D4) */
    pa.depth.load_action = SG_LOADACTION_CLEAR;
    pa.depth.clear_value = 1.0f;
    return pa;
}

/* the default segment renders into the swapchain, or into the capture
   attachments when the platform overrides them (Metal goldens) */
static void begin_default_pass(const float clear[4]) {
    if (P.default_atts.colors[0].id != SG_INVALID_ID) {
        sg_begin_pass(&(sg_pass){
            .action = pipe_pass_action(clear),
            .attachments = P.default_atts,
        });
    } else {
        sg_begin_pass(&(sg_pass){
            .action = pipe_pass_action(clear),
            .swapchain = sglue_swapchain(),
        });
    }
}

void efx_pipeline_set_default_attachments(void *atts) {
    if (atts) {
        P.default_atts = *(sg_attachments *)atts;
    } else {
        memset(&P.default_atts, 0, sizeof(P.default_atts));
    }
}

/* texture coercion (F5a design D1): a sampling handle resolves through the
 * texture registry first, then the render-target registry */
static sg_view view_for_handle(uint64_t h) {
    pipe_tex *t = (pipe_tex *)efx_render_texture_native(h);
    if (t) {
        return t->view;
    }
    pipe_rt *rt = (pipe_rt *)efx_render_target_native(h);
    return rt ? rt->color_tex : (sg_view){0};
}

/* F6b/F6e: get-or-create the cached sampler for a (wrap, filter, mipmaps) set */
static sg_sampler tex_sampler(int wrap, int filter, int mipmaps) {
    if (wrap < 0 || wrap > 2) {
        wrap = EFX_TEX_WRAP_REPEAT;
    }
    if (filter != EFX_FILTER_NEAREST && filter != EFX_FILTER_LINEAR) {
        filter = EFX_FILTER_LINEAR;
    }
    mipmaps = mipmaps ? 1 : 0;
    if (P.tex_smp[wrap][filter][mipmaps].id == SG_INVALID_ID) {
        sg_filter f = filter == EFX_FILTER_NEAREST ? SG_FILTER_NEAREST
                                                   : SG_FILTER_LINEAR;
        sg_wrap w = wrap == EFX_TEX_WRAP_CLAMP
                        ? SG_WRAP_CLAMP_TO_EDGE
                        : wrap == EFX_TEX_WRAP_MIRROR ? SG_WRAP_MIRRORED_REPEAT
                                                      : SG_WRAP_REPEAT;
        P.tex_smp[wrap][filter][mipmaps] = sg_make_sampler(&(sg_sampler_desc){
            .min_filter = f,
            .mag_filter = f,
            .mipmap_filter = mipmaps ? f : SG_FILTER_NEAREST,
            .wrap_u = w,
            .wrap_v = w,
        });
    }
    return P.tex_smp[wrap][filter][mipmaps];
}

/* per-sample sampler: a texture's own sampler, or the default for absent
 * maps / render targets / non-texture handles */
static sg_sampler sampler_for_handle(uint64_t h) {
    pipe_tex *t = (pipe_tex *)efx_render_texture_native(h);
    return t ? tex_sampler(t->wrap, t->filter, t->mipmaps) : P.smp;
}

static void play_mesh_record(const efx_mesh_record *mr, float aspect, int flip) {
    pipe_mesh *m = (pipe_mesh *)efx_render_mesh_native(mr->mesh);
    if (!m) {
        return;
    }
    float mvp[16];
    efx_math_mul(mvp, view_projection(&mr->camera, aspect, flip), mr->transform);
    if (P.depth_remap) {
        /* row 2 of the clip matrix: z' = 0.5*z_clip + 0.5*w_clip maps the
           GL-style (-1..1) range onto the D3D11/Metal (0..1) range;
           monotonic, so depth comparisons and ties are unchanged. Row 3
           carries the perspective w in every column (not just the
           translation), so the fold must cover all four columns
           (ADR 0025). */
        for (int c = 0; c < 4; c++) {
            mvp[c * 4 + 2] = 0.5f * mvp[c * 4 + 2] + 0.5f * mvp[c * 4 + 3];
        }
    }

    vs_params_t vs;
    memcpy(vs.mvp, mvp, sizeof(mvp));
    memcpy(vs.model, mr->transform, sizeof(vs.model));
    efx_math_normal_matrix(vs.normal_mat, mr->transform);

    fs_params_t fs;
    memset(&fs, 0, sizeof(fs));
    fs.tint[0] = mr->color[0];
    fs.tint[1] = mr->color[1];
    fs.tint[2] = mr->color[2];
    fs.tint[3] = mr->color[3];
    fs.camera_pos[0] = mr->camera.pos[0];
    fs.camera_pos[1] = mr->camera.pos[1];
    fs.camera_pos[2] = mr->camera.pos[2];
    for (int i = 0; i < EFX_MAX_POINT_LIGHTS; i++) {
        const efx_point_light *p = &mr->lights.points[i];
        if (!p->enabled) {
            continue;
        }
        fs.point_pos[i][0] = p->pos[0];
        fs.point_pos[i][1] = p->pos[1];
        fs.point_pos[i][2] = p->pos[2];
        fs.point_pos[i][3] = p->range;
        fs.point_color[i][0] = p->color[0];
        fs.point_color[i][1] = p->color[1];
        fs.point_color[i][2] = p->color[2];
        fs.point_color[i][3] = 1.0f;
    }
    if (mr->lights.directional.enabled) {
        fs.dir_dir[0] = mr->lights.directional.dir[0];
        fs.dir_dir[1] = mr->lights.directional.dir[1];
        fs.dir_dir[2] = mr->lights.directional.dir[2];
        fs.dir_dir[3] = 1.0f;
        fs.dir_color[0] = mr->lights.directional.color[0];
        fs.dir_color[1] = mr->lights.directional.color[1];
        fs.dir_color[2] = mr->lights.directional.color[2];
    }

    sg_apply_pipeline(flip ? P.mesh_pip_cw[mr->blend] : P.mesh_pip[mr->blend]);
    sg_apply_uniforms(UB_vs_params, &(sg_range){.ptr = &vs, .size = sizeof(vs)});
    uint64_t white = efx_render_white_texture(); /* absent-map fallback (D3) */
    pipe_tex *white_tex = (pipe_tex *)efx_render_texture_native(white);
    sg_view white_view = white_tex ? white_tex->view : P.white_view;
    for (int i = 0; i < m->surface_count; i++) {
        pipe_mesh_surface *s = &m->surfaces[i];
        if (!s->index_count) {
            continue;
        }
        efx_material mat;
        efx_render_mesh_surface_material(mr->mesh, i, &mat);
        memcpy(fs.ambient, mat.ambient, sizeof(fs.ambient));
        memcpy(fs.diffuse, mat.diffuse, sizeof(fs.diffuse));
        memcpy(fs.specular, mat.specular, sizeof(fs.specular));
        memcpy(fs.emissive, mat.emissive, sizeof(fs.emissive));
        fs.mat_params[0] = mat.shininess;

        /* F4b D3: bind all five maps; absent ones fall back to the engine
           white texture (color maps sample (1,1,1,1); the mask samples
           alpha 1, so it never discards). One shared sampler for all. */
        uint64_t maps[5] = {mat.ambient_map, mat.diffuse_map, mat.specular_map,
                            mat.emissive_map, mat.alpha_mask};
        sg_bindings bnd = {0};
        bnd.vertex_buffers[0] = s->vbuf;
        bnd.index_buffer = s->ibuf;
        for (int k = 0; k < 5; k++) {
            sg_view map_view = view_for_handle(maps[k]);
            bnd.views[k] = map_view.id != SG_INVALID_ID ? map_view : white_view;
            bnd.samplers[k] = sampler_for_handle(maps[k]);
        }
        sg_apply_bindings(&bnd);
        /* documented order: pipeline -> bindings -> uniforms -> draw */
        sg_apply_uniforms(UB_fs_params,
                          &(sg_range){.ptr = &fs, .size = sizeof(fs)});
        sg_draw(0, s->index_count, 1);
    }
}

/* ------------------------------------------------- F5b post passes */

/* scene dimension at the current render scale (rounded up) */
static int post_dim(int surface, float scale) {
    if (surface <= 0) {
        return 1;
    }
    int v = (int)ceilf((float)surface * scale);
    return v < 1 ? 1 : v;
}

/* begin a pass on a target handle (0 = the default surface/capture) */
static void post_begin_pass(uint64_t dst, const float clear[4]) {
    if (!dst) {
        begin_default_pass(clear);
        return;
    }
    pipe_rt *rt = (pipe_rt *)efx_render_target_native(dst);
    if (!rt) {
        begin_default_pass(clear);
        return;
    }
    sg_begin_pass(&(sg_pass){
        .action = pipe_pass_action(clear),
        .attachments = {.colors[0] = rt->color_att,
                        .depth_stencil = rt->depth_att},
    });
}

/* one fullscreen post pass: bind up to two sources, apply the pass's
 * fragment uniforms, draw, end. y-flip follows the destination surface. */
static void post_draw(int prog, uint64_t dst, uint64_t tex_a, uint64_t tex_b,
                      sg_sampler smp_a, sg_sampler smp_b, int has_fs,
                      const void *fs, size_t fs_size) {
    static const float clear[4] = {0, 0, 0, 0};
    post_begin_pass(dst, clear);
    sg_apply_pipeline(P.post_pip[prog]);
    post_vs_params_t vs;
    memset(&vs, 0, sizeof(vs));
    vs.post_params[0] = dst && P.rt_flip ? -1.0f : 1.0f;
    sg_apply_uniforms(UB_post_vs_params, &(sg_range){.ptr = &vs, .size = sizeof(vs)});
    sg_bindings bnd = {0};
    bnd.vertex_buffers[0] = P.post_vbuf;
    bnd.views[0] = view_for_handle(tex_a);
    bnd.samplers[0] = smp_a;
    if (tex_b) {
        bnd.views[1] = view_for_handle(tex_b);
        bnd.samplers[1] = smp_b;
    }
    sg_apply_bindings(&bnd);
    if (has_fs) {
        sg_apply_uniforms(1, &(sg_range){.ptr = fs, .size = fs_size});
    }
    sg_draw(0, 4, 1);
    sg_end_pass();
}

/* execute one chain entry: read `src` (src_w x src_h), write the mixed
 * result to `dst` (0 = default surface). The internal pass structure is
 * registry-owned and invisible to scripts. */
static void run_post_entry(const efx_post_entry *e, uint64_t src, int src_w,
                           int src_h, uint64_t dst) {
    switch (e->effect) {
    case EFX_POST_COLOR_FILTER: {
        post_color_params_t u;
        memset(&u, 0, sizeof(u));
        u.color_params[0] = e->u.color_filter.brightness;
        u.color_params[1] = e->u.color_filter.contrast;
        u.color_params[2] = e->u.color_filter.saturation;
        u.color_params[3] = e->mix;
        memcpy(u.tint, e->u.color_filter.tint, sizeof(u.tint));
        post_draw(POST_COLOR, dst, src, 0, P.smp, P.smp, 1, &u, sizeof(u));
        break;
    }
    case EFX_POST_BLUR: {
        float radius = e->u.blur.radius;
        if (radius > 8.0f) {
            /* downsample chain: blur at half res, then upsample in the mix
               pass (bilinear sampling of the half-size result) */
            int hw = post_dim(src_w, 0.5f), hh = post_dim(src_h, 0.5f);
            uint64_t h0 = efx_render_post_half_target(0, hw, hh);
            uint64_t h1 = efx_render_post_half_target(1, hw, hh);
            if (!h0 || !h1) {
                break;
            }
            post_draw(POST_COPY, h0, src, 0, P.smp, P.smp, 0, NULL, 0);
            post_blur_params_t bu;
            memset(&bu, 0, sizeof(bu));
            bu.blur_dir[0] = (radius * 0.5f) / (4.0f * (float)hw);
            post_draw(POST_BLUR, h1, h0, 0, P.smp, P.smp, 1, &bu, sizeof(bu));
            memset(&bu, 0, sizeof(bu));
            bu.blur_dir[1] = (radius * 0.5f) / (4.0f * (float)hh);
            post_draw(POST_BLUR, h0, h1, 0, P.smp, P.smp, 1, &bu, sizeof(bu));
            post_mix_params_t mu;
            memset(&mu, 0, sizeof(mu));
            mu.mix_params[0] = e->mix;
            post_draw(POST_MIX, dst, src, h0, P.smp, P.smp, 1, &mu, sizeof(mu));
        } else {
            uint64_t t0 = efx_render_post_temp_target(2, src_w, src_h);
            uint64_t t1 = efx_render_post_temp_target(3, src_w, src_h);
            if (!t0 || !t1) {
                break;
            }
            post_blur_params_t bu;
            memset(&bu, 0, sizeof(bu));
            bu.blur_dir[0] = radius / (4.0f * (float)src_w);
            post_draw(POST_BLUR, t0, src, 0, P.smp, P.smp, 1, &bu, sizeof(bu));
            memset(&bu, 0, sizeof(bu));
            bu.blur_dir[1] = radius / (4.0f * (float)src_h);
            post_draw(POST_BLUR, t1, t0, 0, P.smp, P.smp, 1, &bu, sizeof(bu));
            post_mix_params_t mu;
            memset(&mu, 0, sizeof(mu));
            mu.mix_params[0] = e->mix;
            post_draw(POST_MIX, dst, src, t1, P.smp, P.smp, 1, &mu, sizeof(mu));
        }
        break;
    }
    case EFX_POST_BLOOM: {
        /* threshold at half res, blur, then additive composite at full res */
        int hw = post_dim(src_w, 0.5f), hh = post_dim(src_h, 0.5f);
        uint64_t h0 = efx_render_post_half_target(0, hw, hh);
        uint64_t h1 = efx_render_post_half_target(1, hw, hh);
        if (!h0 || !h1) {
            break;
        }
        post_bright_params_t bp;
        memset(&bp, 0, sizeof(bp));
        bp.bright_params[0] = e->u.bloom.threshold;
        post_draw(POST_BRIGHT, h0, src, 0, P.smp, P.smp, 1, &bp, sizeof(bp));
        post_blur_params_t bu;
        memset(&bu, 0, sizeof(bu));
        bu.blur_dir[0] = 2.0f / (float)hw;
        post_draw(POST_BLUR, h1, h0, 0, P.smp, P.smp, 1, &bu, sizeof(bu));
        memset(&bu, 0, sizeof(bu));
        bu.blur_dir[1] = 2.0f / (float)hh;
        post_draw(POST_BLUR, h0, h1, 0, P.smp, P.smp, 1, &bu, sizeof(bu));
        post_composite_params_t cp;
        memset(&cp, 0, sizeof(cp));
        cp.comp_params[0] = e->u.bloom.strength;
        cp.comp_params[1] = e->mix;
        post_draw(POST_COMPOSITE, dst, src, h0, P.smp, P.smp, 1, &cp, sizeof(cp));
        break;
    }
    default:
        break;
    }
}

/* the default target's resolve: run the chain in array order through
 * engine-owned temporaries, or blit the scene when only the render scale
 * changed. `scene` holds the rendered default segment. */
static void run_post_chain(uint64_t scene, int sw, int sh) {
    int count = 0;
    efx_post_entry entries[EFX_POST_MAX_ENTRIES];
    efx_render_post_effects(entries, &count);
    if (count == 0) {
        float scale = 1.0f;
        int filter = EFX_FILTER_LINEAR;
        efx_render_render_scale(&scale, &filter);
        sg_sampler smp = filter == EFX_FILTER_NEAREST ? P.smp_nearest : P.smp;
        post_draw(POST_COPY, 0, scene, 0, smp, smp, 0, NULL, 0);
        return;
    }
    uint64_t src = scene;
    for (int i = 0; i < count; i++) {
        int last = i == count - 1;
        uint64_t dst = last ? 0 : efx_render_post_temp_target(i & 1, sw, sh);
        run_post_entry(&entries[i], src, sw, sh, dst);
        if (!last) {
            src = dst;
        }
    }
}

void efx_pipeline_play(void) {
    if (!P.installed) {
        return;
    }
    int count = 0;
    const efx_record *records = efx_render_records(&count);
    int run_count = 0;
    const efx_draw_run *runs = count > 0 ? efx_render_runs(&run_count) : NULL;
    if (run_count > 0 && !runs) {
        return;
    }

    int vw = 0, vh = 0;
    efx_render_viewport(&vw, &vh);

    /* quad scratch sizing: only the quad records are emitted */
    int quad_count = 0;
    for (int i = 0; i < count; i++) {
        if (records[i].type == EFX_RECORD_QUAD) {
            quad_count++;
        }
    }
    if (quad_count > 0) {
        int cap = quad_count * 6 + 4;
        if (cap > P.scratch_cap) {
            pipe_vertex *grown = realloc(P.scratch, (size_t)cap * sizeof(pipe_vertex));
            if (!grown) {
                return;
            }
            P.scratch = grown;
            P.scratch_cap = cap;
        }
    }

    /* F2 playback: emit ALL quad runs into one dynamic-buffer update
       (multiple updates per frame are unreliable on Metal/D3D11), then
       interleave run draws and mesh records in record order */
    if (run_count > P.run_cap) {
        int cap = P.run_cap ? P.run_cap : 64;
        while (cap < run_count) {
            cap *= 2;
        }
        int *first = realloc(P.run_first, (size_t)cap * sizeof(int));
        int *verts = realloc(P.run_verts, (size_t)cap * sizeof(int));
        if (first) P.run_first = first;
        if (verts) P.run_verts = verts;
        if (!first || !verts) {
            return;
        }
        P.run_cap = cap;
    }
    int *run_first = P.run_first;
    int *run_verts = P.run_verts;
    /* F5b: when a chain is set or the render scale is not 1, the default
       segment renders into the engine-owned implicit scene target (an RT),
       so its records need the GL-family RT y-flip too */
    int post_active = efx_render_post_active();
    float post_scale = 1.0f;
    int post_filter = EFX_FILTER_LINEAR;
    efx_render_render_scale(&post_scale, &post_filter);
    int scene_w = vw, scene_h = vh;
    uint64_t scene = 0;
    if (post_active) {
        scene_w = post_dim(vw, post_scale);
        scene_h = post_dim(vh, post_scale);
        scene = efx_render_post_scene_target(scene_w, scene_h);
    }
    int use_post = post_active && scene != 0;
    uint64_t default_surface = use_post ? scene : 0;
    pipe_vertex *v = P.scratch;
    for (int ri = 0; ri < run_count; ri++) {
        run_first[ri] = (int)(v - P.scratch);
        int start = (int)(v - P.scratch);
        for (int q = 0; q < runs[ri].count; q++) {
            int flip = P.rt_flip &&
                       (use_post ||
                        records[runs[ri].start + q].target != 0);
            if (q > 0) {
                v = emit_quad_bridged(v, &records[runs[ri].start + q].u.quad, flip);
            } else {
                v = emit_quad(v, &records[runs[ri].start + q].u.quad, flip);
            }
        }
        run_verts[ri] = (int)(v - P.scratch) - start;
    }
    int vcount = (int)(v - P.scratch);
    if (vcount > 0) {
        size_t bytes = (size_t)vcount * sizeof(pipe_vertex);
        if (bytes > P.vbuf_size) {
            /* sokol buffers are fixed-size: replace with a larger one
               (updated once per frame, so a fresh buffer is safe here) */
            size_t size = P.vbuf_size;
            while (size < bytes) {
                size *= 2;
            }
            sg_destroy_buffer(P.vbuf);
            P.vbuf = sg_make_buffer(&(sg_buffer_desc){
                .size = size,
                .usage = {.vertex_buffer = true, .dynamic_update = true},
            });
            P.vbuf_size = size;
        }
        sg_update_buffer(P.vbuf, &(sg_range){.ptr = P.scratch, .size = bytes});
    }

    /* pass management (F5a/F5b): the default surface pass opens eagerly
       (clear-only frames render exactly as before); BEGIN/END control
       records switch between the default surface and render-target
       attachments. With post active the default surface is the scene
       target; the chain resolves it to the real default afterwards. */
    float frame_clear[4];
    efx_render_clear_color(frame_clear);
    int cur_w = use_post ? scene_w : vw;
    int cur_h = use_post ? scene_h : vh;
    post_begin_pass(default_surface, frame_clear);
    int run_i = 0;
    for (int i = 0; i < count; i++) {
        const efx_record *r = &records[i];
        if (r->type == EFX_RECORD_BEGIN_TARGET) {
            sg_end_pass();
            pipe_rt *rt =
                (pipe_rt *)efx_render_target_native(r->u.begin_target.target);
            if (rt) {
                sg_begin_pass(&(sg_pass){
                    .action = pipe_pass_action(r->u.begin_target.clear),
                    .attachments = {.colors[0] = rt->color_att,
                                    .depth_stencil = rt->depth_att},
                });
                cur_w = rt->w;
                cur_h = rt->h;
            } else {
                /* unreachable when validation holds: fall back to default */
                post_begin_pass(default_surface, frame_clear);
                cur_w = use_post ? scene_w : vw;
                cur_h = use_post ? scene_h : vh;
            }
            continue;
        }
        if (r->type == EFX_RECORD_END_TARGET) {
            sg_end_pass();
            post_begin_pass(default_surface, frame_clear);
            cur_w = use_post ? scene_w : vw;
            cur_h = use_post ? scene_h : vh;
            continue;
        }
        float aspect =
            (cur_w > 0 && cur_h > 0) ? (float)cur_w / (float)cur_h : 4.0f / 3.0f;
        if (r->type == EFX_RECORD_QUAD) {
            if (run_i < run_count && runs[run_i].start == i) {
                sg_apply_pipeline(P.quad_pip[runs[run_i].blend]);
                sg_bindings bnd = {0};
                bnd.vertex_buffers[0] = P.vbuf;
                sg_view view = view_for_handle(runs[run_i].texture);
                if (view.id != SG_INVALID_ID) {
                    bnd.views[0] = view;
                    bnd.samplers[0] = sampler_for_handle(runs[run_i].texture);
                    sg_apply_bindings(&bnd);
                    sg_draw(run_first[run_i], run_verts[run_i], 1);
                }
                run_i++;
                i += runs[run_i - 1].count - 1;
            }
        } else if (r->type == EFX_RECORD_MESH) {
            play_mesh_record(&r->u.mesh, aspect,
                             P.rt_flip && (use_post || r->target != 0));
        }
    }
    sg_end_pass();
    if (use_post) {
        run_post_chain(scene, scene_w, scene_h);
    }
}

void efx_pipeline_shutdown(void) {
    if (!P.installed) {
        return;
    }
    for (int i = 0; i < 3; i++) {
        sg_destroy_pipeline(P.quad_pip[i]);
        sg_destroy_pipeline(P.mesh_pip[i]);
        sg_destroy_pipeline(P.mesh_pip_cw[i]);
    }
    for (int i = 0; i < POST_PROG_COUNT; i++) {
        sg_destroy_pipeline(P.post_pip[i]);
        sg_destroy_shader(P.post_shd[i]);
    }
    sg_destroy_sampler(P.smp);
    sg_destroy_sampler(P.smp_nearest);
    for (int w = 0; w < 3; w++) {
        for (int f = 0; f < 2; f++) {
            for (int m = 0; m < 2; m++) {
                if (P.tex_smp[w][f][m].id != SG_INVALID_ID) {
                    sg_destroy_sampler(P.tex_smp[w][f][m]);
                }
            }
        }
    }
    sg_destroy_buffer(P.vbuf);
    sg_destroy_buffer(P.post_vbuf);
    sg_destroy_shader(P.quad_shd);
    sg_destroy_shader(P.mesh_shd);
    free(P.scratch);
    free(P.run_first);
    free(P.run_verts);
    memset(&P, 0, sizeof(P));
}
